/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_DEAN;

import DAO_DEAN.CTHoaDonDAO;
import DAO_DEAN.ConnectionDB;
import DAO_DEAN.HoaDonDAO;
import DAO_DEAN.KhachHangDAO;
import DAO_DEAN.SanPhamDAO;
import DAO_DEAN.TaiKhoanDAO;
import DAO_DEAN.TheTVDAO;
import POJO_DEAN.ChiTietHD;
import POJO_DEAN.SanPham;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.parser.JSONParser;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author doanc
 */
public class FormGiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Vector tblDataSP = new Vector();
    Vector tblTitleSP = new Vector();
    Vector tblDataCTHD = new Vector();
    Vector tblTitleCTHD = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<SanPham> dssp = SanPhamDAO.getDSSP_TimKiem();
    static ArrayList<ChiTietHD> dscthd;
    public FormGiaoDien() {
        initComponents();
        setLocationRelativeTo(null);
        bangSP();
        laydulieuSP(dssp);
        setCbo_LoaiGG();
        bangCTHD();
        if(HoaDonDAO.XuatHD_ChuaThanhToan()=="")
            tbl_HoaDon.setModel(new DefaultTableModel(null, tblTitleCTHD));
        else
        {
            lbl_MaHD.setText(HoaDonDAO.XuatHD_ChuaThanhToan());
            dscthd = CTHoaDonDAO.getDSCTHD_MaHD(lbl_MaHD.getText());
            laydulieuCTHD(dscthd);
            XuatGTHD(lbl_MaHD.getText());
        }
        menu.add(panel);
    }
    public void setTenTK(String tenTK){
        lbl_TenTK.setText(tenTK);
        lbl_TaiKhoan.setText(lbl_TenTK.getText());
        txt_password.setText(TaiKhoanDAO.XuatMatKhau(lbl_TaiKhoan.getText()));
        reset_CNQuyen(tenTK);
    }
    
    public void bangSP(){
        tblTitleSP.add("Mã"); tblTitleSP.add("Tên"); 
        tblTitleSP.add("Số lượng"); tblTitleSP.add("ĐVT"); 
        tblTitleSP.add("Giá bán");
    }
    public void laydulieuSP(ArrayList<SanPham> dssp){
        tblDataSP.removeAllElements();
        for(SanPham i : dssp){
            Vector v = new Vector();
            v.add(i.getMasp()); 
            v.add(i.getTensp()); v.add(i.getSl());
            v.add(i.getDvt()); v.add(i.getGiaban());
            tblDataSP.add(v);
            
        }
        tbl_SanPham.setModel(new DefaultTableModel(tblDataSP, tblTitleSP));
    }
    public void bangCTHD(){
        tblTitleCTHD.add("STT"); tblTitleCTHD.add("Mã sản phẩm"); tblTitleCTHD.add("Tên sản phẩm"); 
        tblTitleCTHD.add("Số lượng"); tblTitleCTHD.add("Tổng tiền"); 
    }
    public void laydulieuCTHD(ArrayList<ChiTietHD> dscthd){
        tblDataCTHD.removeAllElements();
        int j = 0;
        for(ChiTietHD i : dscthd){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMasp()); 
            v.add(i.getTensp()); v.add(i.getSoluong());
            v.add(i.getTongtien());
            tblDataCTHD.add(v);
            j++;
        }
        tbl_HoaDon.setModel(new DefaultTableModel(tblDataCTHD, tblTitleCTHD));
    }
    public void setCbo_LoaiGG(){
        String[] x = {"Đ","%"};
        for(String i:x){
            cbo_LoaiGG.addItem(i);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_KH = new javax.swing.JList<>();
        menu = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        backgroundimg = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_TimKiemSP = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_MaHD = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbo_LoaiGG = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        lbl_TongSL = new javax.swing.JLabel();
        lbl_TongTien = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbl_ThanhTien = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btn_ThanhToan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jSpinner_SL = new javax.swing.JSpinner();
        lbl_XoaSPHD = new javax.swing.JLabel();
        txt_GiamGia = new javax.swing.JTextField();
        lbl_Edit_SL = new javax.swing.JLabel();
        lbl_resetGG = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lbl_Hinh = new javax.swing.JLabel();
        lbl_ThemSPHD = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_SanPham = new javax.swing.JTable();
        lbl_ThemKH = new javax.swing.JLabel();
        txt_TimKiemKH = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_QLNV = new javax.swing.JButton();
        btn_QLSP = new javax.swing.JButton();
        btn_QLTK = new javax.swing.JButton();
        btn_QLHD = new javax.swing.JButton();
        btn_QLKH = new javax.swing.JButton();
        btn_QLTheTV = new javax.swing.JButton();
        btn_QLNhaCC = new javax.swing.JButton();
        btn_QLDonDH = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btn_DoiMatKhau = new javax.swing.JButton();
        ckb_HienMK = new javax.swing.JCheckBox();
        txt_password = new javax.swing.JPasswordField();
        lbl_TaiKhoan = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_TenTK = new javax.swing.JLabel();

        panel.setPreferredSize(new java.awt.Dimension(260, 100));

        list_KH.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_KHMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(list_KH);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        menu.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(242, 230, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1532, 805));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(242, 230, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-menu-64.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 90, 50));

        jPanel5.setBackground(new java.awt.Color(242, 230, 255));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel5MouseMoved(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Trang chính");
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel12MouseMoved(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 9, -1, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 60));

        jPanel6.setBackground(new java.awt.Color(242, 230, 255));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel6MouseMoved(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Quản lý");
        jLabel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel14MouseMoved(evt);
            }
        });
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 9, -1, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 60));

        jPanel7.setBackground(new java.awt.Color(242, 230, 255));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel7MouseMoved(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Tài khoản");
        jLabel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel16MouseMoved(evt);
            }
        });
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 9, -1, 40));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 240, 780));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-menu-64.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 70, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-stationery-64.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 74));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-subtract-50.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 20, 60, 70));

        backgroundimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hinh-nen-powerpoint-3d-1.jpg"))); // NOI18N
        backgroundimg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundimgMouseDragged(evt);
            }
        });
        backgroundimg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundimgMousePressed(evt);
            }
        });
        jPanel1.add(backgroundimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1290, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N

        txt_TimKiemSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_TimKiemSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TimKiemSPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_TimKiemSP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 50));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mã hóa đơn :");

        lbl_MaHD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tổng số lượng :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Tổng tiền :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Giảm giá :");

        cbo_LoaiGG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Thành tiền :");

        lbl_TongSL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lbl_TongTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_TongTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("VND");

        lbl_ThanhTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("VND");

        btn_ThanhToan.setBackground(new java.awt.Color(0, 102, 255));
        btn_ThanhToan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pay.png"))); // NOI18N
        btn_ThanhToan.setText("THANH TOÁN");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_HoaDon.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_HoaDon);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Số lượng :");

        jSpinner_SL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinner_SL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_SLKeyTyped(evt);
            }
        });

        lbl_XoaSPHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        lbl_XoaSPHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_XoaSPHDMouseClicked(evt);
            }
        });

        txt_GiamGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_GiamGia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_GiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_GiamGiaKeyTyped(evt);
            }
        });

        lbl_Edit_SL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        lbl_Edit_SL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Edit_SLMouseClicked(evt);
            }
        });

        lbl_resetGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        lbl_resetGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_resetGGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(39, 39, 39))
                                .addGroup(jPanel14Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_resetGG)
                                    .addGap(7, 7, 7)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_TongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_ThanhTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lbl_TongSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addComponent(txt_GiamGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbo_LoaiGG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(btn_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jSpinner_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Edit_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_XoaSPHD)
                        .addGap(0, 252, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbl_MaHD))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner_SL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(lbl_Edit_SL))))
                    .addComponent(lbl_XoaSPHD, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TongSL, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_LoaiGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_GiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_resetGG))
                .addGap(34, 34, 34)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 610, 720));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Hình", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Hinh, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Hinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 150, 170));

        lbl_ThemSPHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addHD.png"))); // NOI18N
        lbl_ThemSPHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ThemSPHDMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_ThemSPHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 70, 60));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Bảng sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        tbl_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_SanPham.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_SanPham);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 650, 550));

        lbl_ThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Them.png"))); // NOI18N
        lbl_ThemKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ThemKHMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_ThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        txt_TimKiemKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_TimKiemKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TimKiemKHKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TimKiemKHKeyTyped(evt);
            }
        });
        jPanel3.add(txt_TimKiemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 260, 32));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/findcustomer.png"))); // NOI18N
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("QUẢN LÝ");

        btn_QLNV.setBackground(new java.awt.Color(255, 0, 102));
        btn_QLNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QLNV.setForeground(new java.awt.Color(255, 255, 255));
        btn_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/QLNV.png"))); // NOI18N
        btn_QLNV.setText("Quản lý nhân viên");
        btn_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNVActionPerformed(evt);
            }
        });

        btn_QLSP.setBackground(new java.awt.Color(255, 0, 102));
        btn_QLSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QLSP.setForeground(new java.awt.Color(255, 255, 255));
        btn_QLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/QLSP.png"))); // NOI18N
        btn_QLSP.setText("Quản lý sản phẩm");
        btn_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLSPActionPerformed(evt);
            }
        });

        btn_QLTK.setBackground(new java.awt.Color(255, 0, 102));
        btn_QLTK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QLTK.setForeground(new java.awt.Color(255, 255, 255));
        btn_QLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/QLTK.png"))); // NOI18N
        btn_QLTK.setText("Quản lý tài khoản");
        btn_QLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLTKActionPerformed(evt);
            }
        });

        btn_QLHD.setBackground(new java.awt.Color(255, 0, 102));
        btn_QLHD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QLHD.setForeground(new java.awt.Color(255, 255, 255));
        btn_QLHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/QLHD.png"))); // NOI18N
        btn_QLHD.setText("Quản lý hóa đơn");
        btn_QLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLHDActionPerformed(evt);
            }
        });

        btn_QLKH.setBackground(new java.awt.Color(255, 0, 102));
        btn_QLKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QLKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_QLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/QLKH.png"))); // NOI18N
        btn_QLKH.setText("Quản lý khách hàng");
        btn_QLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLKHActionPerformed(evt);
            }
        });

        btn_QLTheTV.setBackground(new java.awt.Color(255, 0, 102));
        btn_QLTheTV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QLTheTV.setForeground(new java.awt.Color(255, 255, 255));
        btn_QLTheTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/QLTTV.png"))); // NOI18N
        btn_QLTheTV.setText("Quản lý thẻ thành viên");
        btn_QLTheTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLTheTVActionPerformed(evt);
            }
        });

        btn_QLNhaCC.setBackground(new java.awt.Color(255, 0, 102));
        btn_QLNhaCC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QLNhaCC.setForeground(new java.awt.Color(255, 255, 255));
        btn_QLNhaCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NhaCC.png"))); // NOI18N
        btn_QLNhaCC.setText("Quản lý nhà cung cấp");
        btn_QLNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNhaCCActionPerformed(evt);
            }
        });

        btn_QLDonDH.setBackground(new java.awt.Color(255, 0, 102));
        btn_QLDonDH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_QLDonDH.setForeground(new java.awt.Color(255, 255, 255));
        btn_QLDonDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DonDH.png"))); // NOI18N
        btn_QLDonDH.setText("Quản lý đơn đặt hàng");
        btn_QLDonDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLDonDHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(486, 486, 486)
                        .addComponent(jLabel4))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(btn_QLNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_QLDonDH, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(btn_QLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_QLTheTV, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(btn_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_QLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(btn_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)
                                .addComponent(btn_QLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(46, 46, 46)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_QLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QLTheTV, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_QLNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QLDonDH, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(258, 258, 258))
        );

        jScrollPane1.setViewportView(jPanel16);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("Tài Khoản");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("Tài khoản");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setText("Mật khẩu");

        btn_DoiMatKhau.setBackground(new java.awt.Color(0, 204, 204));
        btn_DoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_DoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btn_DoiMatKhau.setText("Đổi mật khẩu");
        btn_DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoiMatKhauActionPerformed(evt);
            }
        });

        ckb_HienMK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ckb_HienMK.setText("Hiện mật khẩu");
        ckb_HienMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_HienMKActionPerformed(evt);
            }
        });

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_password.setText("jPasswordField1");

        lbl_TaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jLabel24))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(btn_DoiMatKhau))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckb_HienMK)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel30))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                    .addComponent(lbl_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel24)
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lbl_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(ckb_HienMK)
                .addGap(41, 41, 41)
                .addComponent(btn_DoiMatKhau)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel10);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 1290, 770));

        lbl_1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 51, 102));
        lbl_1.setText("Tài khoản :");
        jPanel1.add(lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, 40));

        lbl_TenTK.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_TenTK.setForeground(new java.awt.Color(255, 51, 102));
        jPanel1.add(lbl_TenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int x=240;
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
          if( x==240){
            jPanel2.setSize(240, 700);
            Thread th = new Thread(){
                @Override
                public  void run(){
                    try {
                        for(int i =240;i>=0;i--)
                        {
                            Thread.sleep(1);
                            jPanel2.setSize(i,700);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
            
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    public void create_listSDT(String sdt){
        ArrayList<String> dssdt = KhachHangDAO.listSDT(sdt);
        DefaultListModel modList = new DefaultListModel();
        list_KH.setModel(modList);
        for(String i:dssdt){
            modList.addElement(i);
        }
    }
    private void jLabel12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseMoved

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jPanel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseMoved
        // TODO add your handling code here:
          jPanel5.setBackground(new Color(214,180,248));
    }//GEN-LAST:event_jPanel5MouseMoved

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
        
         jPanel5.setBackground(new Color(242,230,255));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jPanel5MousePressed

    private void jLabel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseMoved

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jPanel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseMoved
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(214,180,248));
        
    }//GEN-LAST:event_jPanel6MouseMoved

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
        
        
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
        
        jPanel6.setBackground(new Color(242,230,255));
        
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jLabel16MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseMoved

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseExited

    private void jPanel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseMoved
        // TODO add your handling code here:
        
         jPanel7.setBackground(new Color(214,180,248));
    }//GEN-LAST:event_jPanel7MouseMoved

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
        
        
          jPanel7.setBackground(new Color(242,230,255));
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);

    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:

        JFrame Frame = new JFrame("Exit");
        //          System.exit(0);
        if (JOptionPane.showConfirmDialog( Frame,"Xác nhận  ","Bạn có muốn đóng chương trình và đăng nhập bằng tài khoản khác ",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
    {
        dispose();
        FormDangNhap sign = new FormDangNhap();
        sign.setVisible(true);
        }
        //System.exit(0);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void backgroundimgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundimgMouseDragged
        // TODO add your handling code here:
//        int x = evt.getXOnScreen();
//        int y = evt.getYOnScreen();
//        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_backgroundimgMouseDragged

    private void backgroundimgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundimgMousePressed
        // TODO add your handling code here:
//        xMouse = evt.getX();
//        yMouse = evt.getY();

    }//GEN-LAST:event_backgroundimgMousePressed

    private void btn_QLDonDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLDonDHActionPerformed
        // TODO add your handling code here:
        close();
        QL_DonDatHang qlddh = new QL_DonDatHang();
        qlddh.setTenTK(lbl_TenTK.getText());
        qlddh.setVisible(true);
    }//GEN-LAST:event_btn_QLDonDHActionPerformed

    private void btn_QLNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNhaCCActionPerformed
        // TODO add your handling code here:
        close();
        QL_NhaCC qlncc = new QL_NhaCC();
        qlncc.setTenTK(lbl_TenTK.getText());
        qlncc.setVisible(true);
    }//GEN-LAST:event_btn_QLNhaCCActionPerformed

    private void btn_QLTheTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLTheTVActionPerformed
        // TODO add your handling code here:
        close();
        QL_TheTV qlt = new QL_TheTV();
        qlt.setTenTK(lbl_TenTK.getText());
        qlt.setVisible(true);
    }//GEN-LAST:event_btn_QLTheTVActionPerformed

    private void btn_QLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLKHActionPerformed
        // TODO add your handling code here:
        close();
        QL_Khach qlk = new QL_Khach();
        qlk.setTenTK(lbl_TenTK.getText());
        qlk.setVisible(true);
    }//GEN-LAST:event_btn_QLKHActionPerformed

    private void btn_QLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLHDActionPerformed
        // TODO add your handling code here:
        close();
        QL_HoaDon qlhd = new QL_HoaDon();
        qlhd.setTenTK(lbl_TenTK.getText());
        qlhd.setVisible(true);
    }//GEN-LAST:event_btn_QLHDActionPerformed

    private void btn_QLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLTKActionPerformed
        // TODO add your handling code here:
        close();
        QL_TaiKhoan qltk = new QL_TaiKhoan();
        qltk.setTenTK(lbl_TenTK.getText());
        qltk.setVisible(true);
    }//GEN-LAST:event_btn_QLTKActionPerformed

    private void btn_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLSPActionPerformed
        // TODO add your handling code here:
        close();
        QL_SanPham qlsp = new QL_SanPham();
        qlsp.setTenTK(lbl_TenTK.getText());
        qlsp.setVisible(true);
    }//GEN-LAST:event_btn_QLSPActionPerformed

    private void btn_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNVActionPerformed
        // TODO add your handling code here:
        close();
        QL_NhanVien qlnv = new QL_NhanVien();
        qlnv.setTenTK(lbl_TenTK.getText());
        qlnv.setVisible(true);
    }//GEN-LAST:event_btn_QLNVActionPerformed

    private void tbl_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SanPhamMouseClicked
        // TODO add your handling code here:
        String masp = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 0).toString();
        String LinkHinh = SanPhamDAO.TimLinkHinh(masp);
        if(LinkHinh!=null){
            ImageIcon imgicon = new ImageIcon(new ImageIcon(LinkHinh).getImage().getScaledInstance(140, 150, Image.SCALE_SMOOTH));
            lbl_Hinh.setIcon(imgicon);
        }
        else
            lbl_Hinh.setIcon(null);
    }//GEN-LAST:event_tbl_SanPhamMouseClicked

    private void lbl_ThemSPHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThemSPHDMouseClicked
        // TODO add your handling code here:
        //        tblTitleCTHD.add("STT"); tblTitleCTHD.add("Mã sản phẩm"); tblTitleCTHD.add("Tên sản phẩm");
        //        tblTitleCTHD.add("Số lượng"); tblTitleCTHD.add("Tổng tiền");

        int n = 100000;
        String mahd = "";
        String tentk = lbl_TenTK.getText().trim();
        String manv = TaiKhoanDAO.XuatMaNV(tentk);
        String quyen = TaiKhoanDAO.XuatQuyen(tentk);
        if(tbl_SanPham.getSelectedRowCount()==1){

            if(!quyen.equals("Admin")){
                String masp = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 0).toString();
                int soluongsp = SanPhamDAO.XuatSL_MaSP(masp);
                if(soluongsp==0)
                JOptionPane.showMessageDialog(this, "Số lượng sản phẩm = 0 nên không thêm được vào hóa đơn !","Thông báo",2);
                else
                {
                    if(lbl_MaHD.getText().equals(""))
                    {

                        for(int i=0;i<n;i++){
                            mahd = "HD"+(i+1);
                            if(HoaDonDAO.XacNhanHD(mahd)==0){
                                break;
                            }
                        }

                        TaoHD(mahd, manv);
                        lbl_MaHD.setText(mahd);
                        TaoCTHD(mahd,masp);
                    }
                    else{
                        TaoCTHD(lbl_MaHD.getText(),masp);
                    }
                }
            }else
                JOptionPane.showMessageDialog(this, "Admin không thể thêm","Thông báo",2);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm cần thêm","Thông báo",2);

    }//GEN-LAST:event_lbl_ThemSPHDMouseClicked

    private void lbl_resetGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_resetGGMouseClicked
        // TODO add your handling code here:
        String macthd = lbl_MaHD.getText();
        int giamgia=0;
        int tongtien = Integer.parseInt(HoaDonDAO.XuatTongTienHD(macthd));

        String loaigg = "";
        if(cbo_LoaiGG.getSelectedIndex()==0){
            loaigg = "Đ";
            giamgia = Integer.parseInt(txt_GiamGia.getText());
            if(giamgia>tongtien){
                giamgia = tongtien;
                txt_GiamGia.setText(""+giamgia);
            }
        }
        else
        {
            loaigg = "%";
            if(Integer.parseInt(txt_GiamGia.getText())>=0 && Integer.parseInt(txt_GiamGia.getText())<=100 ){
                float kq = (float)Integer.parseInt(txt_GiamGia.getText())/100*tongtien;
                giamgia = (int)kq;
            }
            else
            JOptionPane.showMessageDialog(this, "Giảm giá theo % chỉ có thể từ 0 đến 100 !","Thông báo",2);
        }
        System.out.println(giamgia);
        String sql = "update HoaDon set GiamGia = "+giamgia+", LoaiGG = N'"+loaigg+"' where MaHD = '"+macthd+"'\n" +
        "exec ThanhTien '"+macthd+"'";
        HoaDonDAO.ThemXoaSua(sql);
        dscthd = CTHoaDonDAO.getDSCTHD_MaHD(macthd);
        laydulieuCTHD(dscthd);
        String ThanhTien = HoaDonDAO.XuatThanhTien(macthd);
        lbl_ThanhTien.setText(ThanhTien);
    }//GEN-LAST:event_lbl_resetGGMouseClicked

    private void lbl_Edit_SLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Edit_SLMouseClicked
        // TODO add your handling code here:
        String loaigg = cbo_LoaiGG.getSelectedItem().toString();
        String macthd = lbl_MaHD.getText();
        String masp = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 1).toString();
        int sl = Integer.parseInt(jSpinner_SL.getValue().toString());
        String sql_UpdateSLSP = "update CTHD set SoLuongSP = "+sl+" where MaCTHD = '"+macthd+"' and MaSP = '"+masp+"'\n" +
        "exec TongTien '"+macthd+"','"+masp+"'\n"+
        "exec TongSLSP '"+macthd+"'\n"+
        "exec TongTienHD '"+macthd+"'\n"+
        "exec ThanhTien '"+macthd+"'";
        CTHoaDonDAO.ThemXoaSua(sql_UpdateSLSP);
        dscthd = CTHoaDonDAO.getDSCTHD_MaHD(macthd);
        laydulieuCTHD(dscthd);
        XuatGTHD(macthd);
    }//GEN-LAST:event_lbl_Edit_SLMouseClicked

    private void txt_GiamGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GiamGiaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_GiamGiaKeyTyped

    public void reset_CNQuyen(String tk){
        String quyen = TaiKhoanDAO.XuatQuyen(tk);
        if(quyen.equals("Nhân viên kho")){
            btn_QLNV.setEnabled(false);
            btn_QLTK.setEnabled(false);
        }else if(quyen.equals("Nhân viên thu ngân")){
            btn_QLNV.setEnabled(false);
            btn_QLDonDH.setEnabled(false);
            btn_QLSP.setEnabled(false);
            btn_QLTK.setEnabled(false);
        }
    }
    private void lbl_XoaSPHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_XoaSPHDMouseClicked
        // TODO add your handling code here:
        if(tbl_HoaDon.getSelectedRowCount()==1)
        {
            String mahd = lbl_MaHD.getText();
            String masp = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 1).toString();
            String sql =
            "delete from CTHD where MaCTHD='"+mahd+"' and MaSP = '"+masp+"'\n"+
            "exec TongTien '"+mahd+"','"+masp+"'\n"+
            "exec TongSLSP '"+mahd+"'\n"+
            "exec TongTienHD '"+mahd+"'\n"+
            "exec ThanhTien '"+mahd+"'";
            if(CTHoaDonDAO.ThemXoaSua(sql)!=-1){
                System.out.println("Xóa sản phẩm có mã "+masp+" thành công !");
                dscthd = CTHoaDonDAO.getDSCTHD_MaHD(lbl_MaHD.getText());
                laydulieuCTHD(dscthd);
                XuatGTHD(mahd);
                int value = 0;
                jSpinner_SL.setValue(Integer.valueOf(value));
            }else{
                JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
            };

        }else{
            if(tbl_HoaDon.getRowCount()==0)
            JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
            JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_lbl_XoaSPHDMouseClicked

    private void jSpinner_SLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_SLKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jSpinner_SLKeyTyped

    private void tbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonMouseClicked
        // TODO add your handling code here:
        //        tblTitleCTHD.add("STT"); tblTitleCTHD.add("Mã sản phẩm"); tblTitleCTHD.add("Tên sản phẩm");
        //        tblTitleCTHD.add("Số lượng"); tblTitleCTHD.add("Tổng tiền");

        int sl = Integer.parseInt(tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 3).toString());
        jSpinner_SL.setValue(sl);
    }//GEN-LAST:event_tbl_HoaDonMouseClicked

    public int xuatTichDiem(int tt){
        int tichdiem = 0;
        if(tt>=100000 && tt<500000)
            tichdiem = 1;
        else if(tt >=500000 && tt < 1000000)
            tichdiem = 10;
        else if(tt >= 1000000 && tt < 5000000)
            tichdiem = 100;
        else if(tt >= 5000000 && tt < 10000000)
            tichdiem = 1000;
        else if(tt >= 10000000)
            tichdiem = 10000;
        return tichdiem;
    }
    public void QuyTichDiemDeGG(String makh,int tichdiem){
        String macthd = lbl_MaHD.getText();
        
        int tongtien = Integer.parseInt(HoaDonDAO.XuatTongTienHD(macthd));
        int gg = 0;
        if(tichdiem>=100 && tichdiem<500)
        {
            float kq = (float)5/100*tongtien;
            gg = (int)kq;
        }else if(tichdiem>=500 && tichdiem<1000)
        {
            float kq = (float)10/100*tongtien;
            gg = (int)kq;
        }else if(tichdiem>=1000 && tichdiem<5000)
        {
            float kq = (float)15/100*tongtien;
            gg = (int)kq;
        }else if(tichdiem>=5000 && tichdiem<10000)
        {
            float kq = (float)20/100*tongtien;
            gg = (int)kq;
        }else if(tichdiem>=10000 && tichdiem<50000)
        {
            float kq = (float)25/100*tongtien;
            gg = (int)kq;
        }else if(tichdiem>=50000)
        {
            float kq = (float)30/100*tongtien;
            gg = (int)kq;
        }
        String sql = "update HoaDon set GiamGia = "+gg+", LoaiGG = N'%' where MaHD = '"+macthd+"'\n" +
        "exec ThanhTien '"+macthd+"'\n"+
        "update TheTV set TichDiem = TichDiem - "+tichdiem+" where MaKH = '"+makh+"'";
        HoaDonDAO.ThemXoaSua(sql);
        
    }

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thanh toán không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            String tk = lbl_TenTK.getText().trim();
            String quyen = TaiKhoanDAO.XuatQuyen(tk);
            if(quyen=="Admin")
                JOptionPane.showMessageDialog(this, "Admin không thể thanh toán","Thông báo",2);
            else{
                if(KiemTraHangTonKho()!="")
                    JOptionPane.showMessageDialog(this, KiemTraHangTonKho(),"Thông báo",2);
                else{
                    if(txt_TimKiemKH.getText().trim().equals("")){
                        String mahd = lbl_MaHD.getText();
                            if(CTHoaDonDAO.DemSLSP_HD(mahd)==0)
                                JOptionPane.showMessageDialog(this, "Chưa nhập sản phẩm vào hóa đơn","Thông báo",2);
                            else{
                                String sql = "update HoaDon set TGLap = CURRENT_TIMESTAMP, TrangThai=N'Đã thanh toán' where MaHD = '"+mahd+"'";
                                HoaDonDAO.ThemXoaSua(sql);

                                CapNhatToanBoSL_SP();

                                if(JOptionPane.showConfirmDialog(this, "Thanh toán thành công !\n Bạn có muốn in hóa đơn không ?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                                    XuatHD XHD = new XuatHD();
                                    XHD.ThongTinHD(mahd);
                                    XHD.setVisible(true);

                                }

                                if(HoaDonDAO.XuatHD_ChuaThanhToan()==""){
                                    lbl_MaHD.setText("");
                                    lbl_ThanhTien.setText("");
                                    lbl_TongSL.setText("");
                                    lbl_TongTien.setText("");
                                    txt_GiamGia.setText("");
                                    tbl_HoaDon.setModel(new DefaultTableModel(null, tblTitleCTHD));
                                    dssp = SanPhamDAO.getDSSP_TimKiem();
                                    laydulieuSP(dssp);
                                    int value = 0;
                                    jSpinner_SL.setValue(Integer.valueOf(value));
                                }
                                else
                                {
                                    lbl_MaHD.setText(HoaDonDAO.XuatHD_ChuaThanhToan());
                                    dscthd = CTHoaDonDAO.getDSCTHD_MaHD(lbl_MaHD.getText());
                                    laydulieuCTHD(dscthd);
                                    XuatGTHD(lbl_MaHD.getText());
                                    dssp = SanPhamDAO.getDSSP_TimKiem();
                                    laydulieuSP(dssp);
                                    int value = 0;
                                    jSpinner_SL.setValue(Integer.valueOf(value));
                                }
                            }
                    }else{
                        String sdt = txt_TimKiemKH.getText().trim();
                        int ktsdt = KhachHangDAO.TimKiemSDT(sdt);

                        if(ktsdt==1){
                            String makh = KhachHangDAO.XuatMaKH(sdt);
                            String mahd = lbl_MaHD.getText();
                            int tt = Integer.parseInt(HoaDonDAO.XuatThanhTien(mahd));
                            int ktthetv = TheTVDAO.XacNhanTheTV(makh);

                            if(CTHoaDonDAO.DemSLSP_HD(mahd)==0)
                                JOptionPane.showMessageDialog(this, "Chưa nhập sản phẩm vào hóa đơn","Thông báo",2);
                            else{
                                int tichdiem = xuatTichDiem(tt);
                                String sql = "update HoaDon set TGLap = CURRENT_TIMESTAMP, TrangThai=N'Đã thanh toán', MaKH = '"+makh+"' where MaHD = '"+mahd+"'\n";
                                HoaDonDAO.ThemXoaSua(sql);

                                CapNhatToanBoSL_SP();

                                if(ktthetv==1)
                                {
                                    String sql_CapNhatTD = "update TheTV set TichDiem = TichDiem + "+tichdiem+" where MaKH = '"+makh+"'";
                                    TheTVDAO.ThemXoaSua(sql_CapNhatTD);

                                }

                                int td = TheTVDAO.XuatTichDiem(makh);
                                if(td>=100){
                                    if(JOptionPane.showConfirmDialog(this, "Tích điểm hiện tại của khách đã đủ để giảm giá, bạn có muốn giảm không ?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                                        QuyTichDiemDeGG(makh, tichdiem);
                                        String gghd = HoaDonDAO.XuatGiamGia(mahd);
                                        String[] giamgia = gghd.split(" ");
                                        int tichdiemcon = TheTVDAO.XuatTichDiem(makh);
                                        JOptionPane.showMessageDialog(this, "Đã giảm "+giamgia[0]+" Đ -> thành tiền còn lại "+HoaDonDAO.XuatThanhTien(mahd)+"\n Tích điểm còn lại: "+tichdiemcon+"","Thông báo",2);
                                    }
                                }


                                if(JOptionPane.showConfirmDialog(this, "Thanh toán thành công !\n Bạn có muốn in hóa đơn không ?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                                    XuatHD XHD = new XuatHD();
                                    XHD.ThongTinHD(mahd);
                                    XHD.setVisible(true);
                                }

                                if(HoaDonDAO.XuatHD_ChuaThanhToan()==""){
                                    lbl_MaHD.setText("");
                                    lbl_ThanhTien.setText("");
                                    lbl_TongSL.setText("");
                                    lbl_TongTien.setText("");
                                    txt_GiamGia.setText("");
                                    tbl_HoaDon.setModel(new DefaultTableModel(null, tblTitleCTHD));
                                    dssp = SanPhamDAO.getDSSP_TimKiem();
                                    laydulieuSP(dssp);
                                    int value = 0;
                                    jSpinner_SL.setValue(Integer.valueOf(value));
                                }
                                else
                                {
                                    lbl_MaHD.setText(HoaDonDAO.XuatHD_ChuaThanhToan());
                                    dscthd = CTHoaDonDAO.getDSCTHD_MaHD(lbl_MaHD.getText());
                                    laydulieuCTHD(dscthd);
                                    XuatGTHD(lbl_MaHD.getText());
                                    dssp = SanPhamDAO.getDSSP_TimKiem();
                                    laydulieuSP(dssp);
                                    int value = 0;
                                    jSpinner_SL.setValue(Integer.valueOf(value));
                                }
                            }
                        }else{
                            JOptionPane.showMessageDialog(this, "Không có số điện thoại này !","Thông báo",2);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void txt_TimKiemSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimKiemSPKeyReleased
        // TODO add your handling code here:
        String search = txt_TimKiemSP.getText().toLowerCase().trim();
        ArrayList<SanPham> ResultSearch= new ArrayList<SanPham>();
        ResultSearch = SanPhamDAO.TimKiemTenSP(search);
        laydulieuSP(ResultSearch);
    }//GEN-LAST:event_txt_TimKiemSPKeyReleased

    private void ckb_HienMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_HienMKActionPerformed
        // TODO add your handling code here:
        if(ckb_HienMK.isSelected())
            txt_password.setEchoChar((char)0);
        else
            txt_password.setEchoChar('*');
    }//GEN-LAST:event_ckb_HienMKActionPerformed

    private void btn_DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoiMatKhauActionPerformed
        // TODO add your handling code here:
        if(txt_password.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống !");
        else{
            String tentk = lbl_TaiKhoan.getText();
            String matkhau = txt_password.getText().trim();
            String sql="update TaiKhoan set MatKhau = '"+matkhau+"' where TenTK = '"+tentk+"'";
            if(TaiKhoanDAO.ThemXoaSua(sql)!=-1){
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công !");
                txt_password.setText(TaiKhoanDAO.XuatMatKhau(lbl_TaiKhoan.getText()));
            }else{
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu lỗi !");
            }
        }
    }//GEN-LAST:event_btn_DoiMatKhauActionPerformed

    private void txt_TimKiemKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimKiemKHKeyReleased
        // TODO add your handling code here:
        String search = txt_TimKiemKH.getText().trim();
        if(!search.equals("")){
            create_listSDT(search);
            menu.show(txt_TimKiemKH,0,txt_TimKiemKH.getHeight());
            
        }
    }//GEN-LAST:event_txt_TimKiemKHKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if( x==0){
            jPanel2.show();
            jPanel2.setSize(x,700);
            Thread th = new Thread(){
                @Override
                public  void run(){
                    try {
                        for(int i =0;i<=x;i++)
                        {
                            Thread.sleep(1);
                            jPanel2.setSize(i,700);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=240;

        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_TimKiemKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimKiemKHKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_TimKiemKHKeyTyped

    private void list_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_KHMouseClicked
        // TODO add your handling code here:
        String sdt = list_KH.getSelectedValue();
        txt_TimKiemKH.setText(sdt);
    }//GEN-LAST:event_list_KHMouseClicked

    private void lbl_ThemKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThemKHMouseClicked
        // TODO add your handling code here:
        close();
        QL_Khach qlk = new QL_Khach();
        qlk.setTenTK(lbl_TenTK.getText());
        qlk.setVisible(true);
    }//GEN-LAST:event_lbl_ThemKHMouseClicked

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    public void TaoHD(String mahd, String manv){
        
        String sql = "insert into HoaDon(MaHD,MaNV) values('"+mahd+"','"+manv+"')";
        int kq=HoaDonDAO.ThemXoaSua(sql);
        if(kq!=-1){
            System.out.println("Thêm hóa đơn "+mahd+" thành công !");
        }
    }
    public void XuatGTHD(String mahd){
        String TongSL = HoaDonDAO.XuatTongSL(mahd);
        String TongTien = HoaDonDAO.XuatTongTienHD(mahd);
        String ThanhTien = HoaDonDAO.XuatThanhTien(mahd);
        String[] chuoiso = HoaDonDAO.XuatGiamGia(mahd).split(" ");
        String GiamGia = chuoiso[0];
        
        lbl_TongSL.setText(TongSL);
        lbl_TongTien.setText(TongTien);
        txt_GiamGia.setText(GiamGia);
        lbl_ThanhTien.setText(ThanhTien);
        
    }
    public void TaoCTHD(String macthd, String masp){
//        tblTitleCTHD.add("STT"); tblTitleCTHD.add("Mã sản phẩm"); tblTitleCTHD.add("Tên sản phẩm"); 
//        tblTitleCTHD.add("Số lượng"); tblTitleCTHD.add("Tổng tiền");
        String loaigg = cbo_LoaiGG.getSelectedItem().toString();
        String sql = "insert into CTHD(MaCTHD,MaSP) values('"+macthd+"','"+masp+"')\n" +
                     "exec TongTien '"+macthd+"','"+masp+"'\n"+
                     "exec TongSLSP '"+macthd+"'\n"+
                     "exec TongTienHD '"+macthd+"'\n"+
                     "exec ThanhTien '"+macthd+"'";
        int kq=CTHoaDonDAO.ThemXoaSua(sql);
        if(kq!=-1){
            System.out.println("Thêm sản phẩm mã "+masp+" vào hóa đơn mã "+macthd+" thành công !");
        }
        else{
            String sql_UpdateSLSP = "update CTHD set SoLuongSP = SoLuongSP + 1 where MaCTHD = '"+macthd+"' and MaSP = '"+masp+"'\n" +
                     "exec TongTien '"+macthd+"','"+masp+"'\n"+
                     "exec TongSLSP '"+macthd+"'\n"+
                     "exec TongTienHD '"+macthd+"'\n"+
                     "exec ThanhTien '"+macthd+"'";
            CTHoaDonDAO.ThemXoaSua(sql_UpdateSLSP);
        }
        dscthd = CTHoaDonDAO.getDSCTHD_MaHD(lbl_MaHD.getText());
            laydulieuCTHD(dscthd);
        XuatGTHD(macthd);
    }
    
    public void clearAllTextField(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JTextField){
                JTextField f = (JTextField)c;
                f.setText("");
            }
            else if(c instanceof Container)
                clearAllTextField((Container)c);
        }
    }
    public String KiemTraHangTonKho(){
//        tblTitleCTHD.add("STT"); tblTitleCTHD.add("Mã sản phẩm"); tblTitleCTHD.add("Tên sản phẩm"); 
//        tblTitleCTHD.add("Số lượng"); tblTitleCTHD.add("Tổng tiền");

        String sp = "";
        for(int i=0;i<tbl_HoaDon.getRowCount();i++){
            String masp = tbl_HoaDon.getValueAt(i, 1).toString();
            String tensp = tbl_HoaDon.getValueAt(i, 2).toString();
            int soluongsp = Integer.parseInt(tbl_HoaDon.getValueAt(i, 3).toString());
            if(soluongsp>SanPhamDAO.XuatSL_MaSP(masp)){
                sp="Mã sản phẩm: "+masp+"\n Tên sản phẩm: "+tensp+"\n Số lượng mua: "+soluongsp+"\n=> Sản phẩm này có số lượng mua vượt quá số lượng tồn kho !";
                break;
            }
        }
        return sp;
    }
    public void CapNhatToanBoSL_SP(){
        
        for(int i=0;i<tbl_HoaDon.getRowCount();i++){
            String masp = tbl_HoaDon.getValueAt(i, 1).toString();
            int soluongsp = Integer.parseInt(tbl_HoaDon.getValueAt(i, 3).toString());
            
            String sql_CapNhatSL = "exec CapNhatSLSP '"+masp+"',"+soluongsp+"";
            CTHoaDonDAO.ThemXoaSua(sql_CapNhatSL);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGiaoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundimg;
    private javax.swing.JButton btn_DoiMatKhau;
    private javax.swing.JButton btn_QLDonDH;
    private javax.swing.JButton btn_QLHD;
    private javax.swing.JButton btn_QLKH;
    private javax.swing.JButton btn_QLNV;
    private javax.swing.JButton btn_QLNhaCC;
    private javax.swing.JButton btn_QLSP;
    private javax.swing.JButton btn_QLTK;
    private javax.swing.JButton btn_QLTheTV;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JComboBox<String> cbo_LoaiGG;
    private javax.swing.JCheckBox ckb_HienMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner_SL;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_Edit_SL;
    private javax.swing.JLabel lbl_Hinh;
    private javax.swing.JLabel lbl_MaHD;
    private javax.swing.JLabel lbl_TaiKhoan;
    private javax.swing.JLabel lbl_TenTK;
    private javax.swing.JLabel lbl_ThanhTien;
    private javax.swing.JLabel lbl_ThemKH;
    private javax.swing.JLabel lbl_ThemSPHD;
    private javax.swing.JLabel lbl_TongSL;
    private javax.swing.JLabel lbl_TongTien;
    private javax.swing.JLabel lbl_XoaSPHD;
    private javax.swing.JLabel lbl_resetGG;
    private javax.swing.JList<String> list_KH;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbl_HoaDon;
    private javax.swing.JTable tbl_SanPham;
    private javax.swing.JTextField txt_GiamGia;
    private javax.swing.JTextField txt_TimKiemKH;
    private javax.swing.JTextField txt_TimKiemSP;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables

//    private void Seticon() {
//        //To change body of generated methods, choose Tools | Templates.
//       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconform.png")));
//    }
}
