/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI_DEAN;

import DAO_DEAN.SanPhamDAO;
import DAO_DEAN.CTDonDHDAO;
import DAO_DEAN.DonDatHangDAO;
import DAO_DEAN.NhaCCDAO;
import DAO_DEAN.TaiKhoanDAO;
import POJO_DEAN.ChiTietDDH;
import POJO_DEAN.NhaCC;
import POJO_DEAN.SanPham;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.Buffer;
import java.util.ArrayList;
import java.util.Vector;
import javafx.scene.control.Cell;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author tandat
 */
public class QL_CTDonDatHang extends javax.swing.JFrame {

    /** Creates new form QL_HoaDon */
    Vector tblDataSP = new Vector();
    Vector tblTitleSP = new Vector();
    Vector tblDataCTDonHang = new Vector();
    Vector tblTitleCTDonHang = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<ChiTietDDH> dsctddh ;
    static ArrayList<SanPham> dssp = SanPhamDAO.getDSSP();
    public QL_CTDonDatHang() {
        initComponents();
        setLocationRelativeTo(null);
        txtA_SanPham.setLineWrap(true);
        bangSP();
        laydulieuSP(dssp);
    }

    public void ThongTinDDH(String madon,String mancc,String nv,String tongslspd,String ngaydh,String trangthaidh,String capnhattk){
        lbl_MaDH.setText(madon);
        txt_MaNCC.setText(mancc);
        txt_NhanVien.setText(nv);
        txt_TongSLSPD.setText(tongslspd);
        lbl_NgayDatHang.setText(ngaydh);
        lbl_TrangThaiDH.setText(trangthaidh);
        lbl_CapNhatTonKho.setText(capnhattk);
        String kq = NhaCCDAO.ThongTinNhaCC(mancc);
        txtA_NhaCC.setText(kq);
        bangCTDDH();
        dsctddh = CTDonDHDAO.getDSCTDDH(madon);
        laydulieuCTDDH(dsctddh);
    }
    public void setTenTK(String tenTK){
        lbl_TenTK.setText(tenTK);
    }
    public void bangSP(){
        tblTitleSP.add("STT"); tblTitleSP.add("Mã"); tblTitleSP.add("Tên"); 
        tblTitleSP.add("Số lượng"); tblTitleSP.add("Đơn vị tính"); 
        tblTitleSP.add("Giá bán"); tblTitleSP.add("Giá nhập");
        tblTitleSP.add("Loại sản phẩm"); tblTitleSP.add("Thương hiệu");
    }
    public void laydulieuSP(ArrayList<SanPham> dssp){
        tblDataSP.removeAllElements();
        int j = 0;
        for(SanPham i : dssp){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMasp()); 
            v.add(i.getTensp()); v.add(i.getSl());
            v.add(i.getDvt()); v.add(i.getGiaban()); 
            v.add(i.getGianhap()); v.add(i.getLoaisp()); 
            v.add(i.getThuonghieu());
            tblDataSP.add(v);
            j++;
        }
        tbl_SanPham.setModel(new DefaultTableModel(tblDataSP, tblTitleSP));
    }
    public void bangCTDDH(){
        tblTitleCTDonHang.add("STT"); tblTitleCTDonHang.add("Mã sản phẩm"); 
        tblTitleCTDonHang.add("Tên sản phẩm"); tblTitleCTDonHang.add("Số lượng"); 
    }
    public void laydulieuCTDDH(ArrayList<ChiTietDDH> dsctddh){
        tblDataCTDonHang.removeAllElements();
        int j = 0;
        for(ChiTietDDH i : dsctddh){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMasp()); 
            v.add(i.getTensp()); v.add(i.getSoluongdat());

            tblDataCTDonHang.add(v);
            j++;
        }
        tbl_CTDonDatHang.setModel(new DefaultTableModel(tblDataCTDonHang, tblTitleCTDonHang));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_XuatFile = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_NgayDatHang = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_MaNCC = new javax.swing.JLabel();
        txt_TongSLSPD = new javax.swing.JLabel();
        txt_NhanVien = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_NhaCC = new javax.swing.JTextArea();
        btn_CapNhatTK = new javax.swing.JButton();
        lbl_TrangThaiDH = new javax.swing.JLabel();
        lbl_CapNhatTonKho = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_TenTK = new javax.swing.JLabel();
        lbl_BangHD1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_CTDonDatHang = new javax.swing.JTable();
        lbl_BangHD = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_SanPham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_SanPham = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        lbl_Hinh = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_MaDH = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_MaSP = new javax.swing.JTextField();
        txt_SoLuongSPD = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_TenSP = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lbl_STT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHI TIẾT ĐƠN ĐẶT HÀNG");

        jPanel1.setLayout(new java.awt.GridLayout(1, 6, 2, 6));

        btn_Them.setBackground(new java.awt.Color(255, 0, 102));
        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Them.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Them);

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 102));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Xoa.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Xoa);

        btn_Sua.setBackground(new java.awt.Color(255, 0, 102));
        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sua.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sua);

        btn_XuatFile.setBackground(new java.awt.Color(255, 0, 102));
        btn_XuatFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_XuatFile.setForeground(new java.awt.Color(255, 255, 255));
        btn_XuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/XemChiTiet.png"))); // NOI18N
        btn_XuatFile.setText("Xuất File Excel");
        btn_XuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XuatFileActionPerformed(evt);
            }
        });
        jPanel1.add(btn_XuatFile);

        btn_Thoat.setBackground(new java.awt.Color(255, 0, 102));
        btn_Thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Thoat.png"))); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Thoat);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Thông tin đơn đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Mã nhà cung cấp");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Tổng số lượng sản phẩm đặt");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Ngày đặt hàng");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Trạng thái đặt hàng");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Cập nhật tồn kho");

        lbl_NgayDatHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Nhân viên");

        txt_MaNCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txt_TongSLSPD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txt_NhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)), "Thông tin nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtA_NhaCC.setColumns(20);
        txtA_NhaCC.setRows(5);
        jScrollPane2.setViewportView(txtA_NhaCC);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        btn_CapNhatTK.setBackground(new java.awt.Color(255, 0, 102));
        btn_CapNhatTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_CapNhatTK.setForeground(new java.awt.Color(255, 255, 255));
        btn_CapNhatTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CapNhat.png"))); // NOI18N
        btn_CapNhatTK.setText("Cập nhật tồn kho");
        btn_CapNhatTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatTKActionPerformed(evt);
            }
        });

        lbl_TrangThaiDH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lbl_CapNhatTonKho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txt_MaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addGap(23, 23, 23))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txt_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_TongSLSPD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_NgayDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(12, 12, 12)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_CapNhatTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(lbl_TrangThaiDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CapNhatTK, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txt_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txt_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_TongSLSPD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NgayDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(lbl_TrangThaiDH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(lbl_CapNhatTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CapNhatTK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        lbl_1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 51, 102));
        lbl_1.setText("Tài khoản :");

        lbl_TenTK.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_TenTK.setForeground(new java.awt.Color(255, 51, 102));

        lbl_BangHD1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Bảng chi tiết đơn đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        tbl_CTDonDatHang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_CTDonDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_CTDonDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CTDonDatHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_CTDonDatHang);

        javax.swing.GroupLayout lbl_BangHD1Layout = new javax.swing.GroupLayout(lbl_BangHD1);
        lbl_BangHD1.setLayout(lbl_BangHD1Layout);
        lbl_BangHD1Layout.setHorizontalGroup(
            lbl_BangHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        lbl_BangHD1Layout.setVerticalGroup(
            lbl_BangHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        lbl_BangHD.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Bảng sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        tbl_SanPham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_SanPham);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)), "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtA_SanPham.setColumns(20);
        txtA_SanPham.setRows(5);
        jScrollPane1.setViewportView(txtA_SanPham);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Hình", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Hinh, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Hinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lbl_BangHDLayout = new javax.swing.GroupLayout(lbl_BangHD);
        lbl_BangHD.setLayout(lbl_BangHDLayout);
        lbl_BangHDLayout.setHorizontalGroup(
            lbl_BangHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_BangHDLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(lbl_BangHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbl_BangHDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lbl_BangHDLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        lbl_BangHDLayout.setVerticalGroup(
            lbl_BangHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(lbl_BangHDLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Mã đơn đặt hàng :");

        lbl_MaDH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_MaDH.setForeground(new java.awt.Color(255, 51, 51));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Thông tin chi tiết đơn đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Mã sản phẩm");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Số lượng đặt");

        txt_MaSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_SoLuongSPD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Sản phẩm");

        txt_TenSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("STT");

        lbl_STT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_STT.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(txt_SoLuongSPD)
                    .addComponent(lbl_STT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_TenSP))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lbl_STT, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SoLuongSPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(286, 286, 286)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_MaDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_BangHD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_BangHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_MaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_BangHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_BangHD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SanPhamMouseClicked
        // TODO add your handling code here:
        String STT = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 0).toString();
        String masp = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 1).toString();
        String tensp = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 2).toString();
        String sl = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 3).toString();
        String dvt = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 4).toString();
        String giaban = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 5).toString();
        String gianhap = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 6).toString();
        String loaisp = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 7).toString();
        String thuonghieu = tbl_SanPham.getValueAt(tbl_SanPham.getSelectedRow(), 8).toString();
  
        txt_MaSP.setText(masp);
        txtA_SanPham.setText("STT: "+STT+"\n\nMã: "+masp+"\n\nTên sản phẩm: "
                +tensp+"\n\nSố lượng: "+sl+"\n\nĐơn vị tính: "+dvt+"\n\nGiá bán: "+giaban+"\n\nGiá nhập: "
                +gianhap+"\n\nLoại: "+loaisp+"\n\nThương hiệu: "+thuonghieu);
            
        String LinkHinh = SanPhamDAO.TimLinkHinh(masp);
        if(LinkHinh!=null){
            ImageIcon imgicon = new ImageIcon(new ImageIcon(LinkHinh).getImage().getScaledInstance(140, 150, Image.SCALE_SMOOTH));
            lbl_Hinh.setIcon(imgicon);
        }
        else
            lbl_Hinh.setIcon(null);
    }//GEN-LAST:event_tbl_SanPhamMouseClicked

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        String trangthaidh = lbl_TrangThaiDH.getText().trim();
        if(txt_MaSP.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Mã sản phẩm không được để trống !","Thông báo",2);
        else
        {
            if(tbl_CTDonDatHang.getSelectedRowCount()==1)
            {
                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    if(trangthaidh.equals("Chưa đặt")){
                        String maddh = lbl_MaDH.getText().trim();
                        String masp = txt_MaSP.getText().trim();
                        String sql = "delete CTDonDatHang where MaDonDH = '"+maddh+"' and MaSP='"+masp+"'\n"+
                                    "exec CapNhatTongSLSPD '"+maddh+"'";

                        if(CTDonDHDAO.ThemXoaSua(sql)!=-1)
                        {
                            clearAllTextField(this.getContentPane());
                            returnDefaultAllCbo(this.getContentPane());
                            dsctddh = CTDonDHDAO.getDSCTDDH(maddh);
                            laydulieuCTDDH(dsctddh);
                            JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                            int tongslspd = DonDatHangDAO.XuatTongSLSPDat(maddh);
                            txt_TongSLSPD.setText(tongslspd+"");
                        }
                        else
                            JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
                    }else
                        JOptionPane.showMessageDialog(this, "Đơn hàng đã đặt không thể xóa !", "Thông báo", 2);
                }
            }else{
                if(tbl_CTDonDatHang.getRowCount()==0)
                    JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
                else
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_XuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XuatFileActionPerformed
        // TODO add your handling code here:
        FileOutputStream execlFOU = null;
        BufferedOutputStream excelBOU = null;
        XSSFWorkbook exceltblExport = null;
        
        JFileChooser excelFileChooser = new JFileChooser("D:\\");
        excelFileChooser.setDialogTitle("Save as");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXECL FILES","xls","xlsx","xlsm");
        excelFileChooser.setFileFilter(fnef);
        int execlchooser = excelFileChooser.showSaveDialog(null);
        
        if(execlchooser==JFileChooser.APPROVE_OPTION){
            
            try {
                exceltblExport = new XSSFWorkbook();
                XSSFSheet excelSheet = exceltblExport.createSheet("Danh sách sản phẩm đặt");
                
               
                
                for(int i=0;i<tbl_CTDonDatHang.getRowCount();i++){
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for(int j=0;j<tbl_CTDonDatHang.getColumnCount();j++){
                        XSSFCell execlCell = excelRow.createCell(j);
                        execlCell.setCellValue(tbl_CTDonDatHang.getValueAt(i, j).toString());
                    }
                }   
                execlFOU = new FileOutputStream(excelFileChooser.getSelectedFile()+ ".xlsx");
                excelBOU = new BufferedOutputStream(execlFOU);
                exceltblExport.write(excelBOU);
                JOptionPane.showMessageDialog(this, "Xuất File thành công !");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    if(excelBOU != null){
                        excelBOU.close();
                    }
                    if(execlFOU != null){
                        execlFOU.close();
                    }
                    if(exceltblExport!=null){
                        exceltblExport.close();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
            
        }
        
    }//GEN-LAST:event_btn_XuatFileActionPerformed

    public void returnDefaultAllCbo(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JComboBox){
                JComboBox f = (JComboBox)c;
                f.setSelectedIndex(0);
            }
            else if(c instanceof Container)
                returnDefaultAllCbo((Container)c);
        }
    }
    public void clearAllTextField(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JTextField){
                JTextField f = (JTextField)c;
                f.setText("");
            }
            else if(c instanceof Container)
                clearAllTextField((Container)c);
        }
    }
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        close();
        QL_DonDatHang qlddh = new QL_DonDatHang();
        qlddh.setTenTK(lbl_TenTK.getText());
        qlddh.setVisible(true);
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        String madon = lbl_MaDH.getText().trim();
        String masp = txt_MaSP.getText().trim();
        String sl = txt_SoLuongSPD.getText().trim();
        String trangthaidh = lbl_TrangThaiDH.getText().trim();
        if(masp.equals("") || sl.equals(""))
            JOptionPane.showMessageDialog(this, "Mã sản phẩm hoặc số lượng đặt không được để trống !", "Thông báo", 2);
        else{
            if(tbl_CTDonDatHang.getSelectedRowCount()==1)
                {
                    if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                        if(trangthaidh.equals("Chưa đặt")){
                            int solgd = Integer.parseInt(sl);
                            String sql = "update CTDonDatHang\n" +
                            "set SoLuongSPD = "+solgd+"\n" +
                            "where MaDonDH = '"+madon+"' and MaSP ='"+masp+"'\n"+
                            "exec CapNhatTongSLSPD '"+madon+"'";
                            CTDonDHDAO.ThemXoaSua(sql);
                            dsctddh = CTDonDHDAO.getDSCTDDH(madon);
                            laydulieuCTDDH(dsctddh);
                            JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
                            int tongslspd = DonDatHangDAO.XuatTongSLSPDat(madon);
                            txt_TongSLSPD.setText(tongslspd+"");
                        }else
                            JOptionPane.showMessageDialog(this, "Đơn hàng đã đặt không thể sửa !", "Thông báo", 2);
                    }
                }else{
                    if(tbl_CTDonDatHang.getRowCount()==0)
                        JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
                    else
                        JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
                }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void tbl_CTDonDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CTDonDatHangMouseClicked
        // TODO add your handling code here:
        String STT = tbl_CTDonDatHang.getValueAt(tbl_CTDonDatHang.getSelectedRow(), 0).toString();
        String masp = tbl_CTDonDatHang.getValueAt(tbl_CTDonDatHang.getSelectedRow(), 1).toString();
        String tensp = tbl_CTDonDatHang.getValueAt(tbl_CTDonDatHang.getSelectedRow(), 2).toString();
        String solg = tbl_CTDonDatHang.getValueAt(tbl_CTDonDatHang.getSelectedRow(), 3).toString();

        lbl_STT.setText(STT);
        txt_MaSP.setText(masp);
        txt_TenSP.setText(tensp);
        txt_SoLuongSPD.setText(solg);
        
    }//GEN-LAST:event_tbl_CTDonDatHangMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        String madon = lbl_MaDH.getText().trim();
        String masp = txt_MaSP.getText().trim();
        String sl = txt_SoLuongSPD.getText().trim();
        String trangthaidh = lbl_TrangThaiDH.getText().trim();
        
        if(masp.equals("")||sl.equals(""))
            JOptionPane.showMessageDialog(this, "Mã sản phẩm hoặc số lượng đặt không được để trống !", "Thông báo", 2);
        else{
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không ?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

                if(trangthaidh.equals("Chưa đặt")){
                        int solgd = Integer.parseInt(sl);
                        String sql = "insert into CTDonDatHang(MaDonDH,MaSP,SoLuongSPD) values\n" +
                                    "('"+madon+"','"+masp+"',"+solgd+")\n"+
                                    "exec CapNhatTongSLSPD '"+madon+"'";
                        int kq=CTDonDHDAO.ThemXoaSua(sql);
                        if(kq!=-1)
                        {
                            dsctddh = CTDonDHDAO.getDSCTDDH(madon);
                            laydulieuCTDDH(dsctddh);
                            JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
                            int tongslspd = DonDatHangDAO.XuatTongSLSPDat(madon);
                            txt_TongSLSPD.setText(tongslspd+"");
                        }
                        else
                             JOptionPane.showMessageDialog(this, "Mã đơn hàng và mã sản phẩm này đã tồn tại !", "Thông báo", 2);

                }else{
                    JOptionPane.showMessageDialog(this, "Đơn hàng đã đặt không thể thêm !", "Thông báo", 2);
                }
            }
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_CapNhatTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatTKActionPerformed
        // TODO add your handling code here:
        String capnhattk = lbl_CapNhatTonKho.getText().trim();
        if(capnhattk=="Đã cập nhật"){
            JOptionPane.showMessageDialog(this, "Đã cập nhật tồn kho rồi !", "Thông báo", 2);
        }else{
            String trangthaidat = lbl_TrangThaiDH.getText().trim();
            if(trangthaidat.equals("Chưa đặt"))
                JOptionPane.showMessageDialog(this, "Chưa đặt nên chưa cập nhật tồn kho được !", "Thông báo", 2);
            else{
                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật tồn kho ?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    String madh = lbl_MaDH.getText().trim();
                    for(int i=0;i<tbl_CTDonDatHang.getRowCount();i++){
                        String masp = tbl_CTDonDatHang.getValueAt(i, 1).toString();
                        int solg = Integer.parseInt(tbl_CTDonDatHang.getValueAt(i, 3).toString());
                        String sql = "exec CapNhatSLSP_XoaHD '"+masp+"',"+solg+"";
                        CTDonDHDAO.ThemXoaSua(sql);        
                    }
                    String sql_CapNhatTK = "update DonDatHang set CapNhatTonKho = N'Đã cập nhật' where MaDonDH = '"+madh+"'";
                    CTDonDHDAO.ThemXoaSua(sql_CapNhatTK);
                    dssp = SanPhamDAO.getDSSP();
                    laydulieuSP(dssp);
                    String CNTK = DonDatHangDAO.XuatCNTK(madh);
                    lbl_CapNhatTonKho.setText(CNTK);
                }
            }
        }
    }//GEN-LAST:event_btn_CapNhatTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_CTDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_CTDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_CTDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_CTDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_CTDonDatHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhatTK;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XuatFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JPanel lbl_BangHD;
    private javax.swing.JPanel lbl_BangHD1;
    private javax.swing.JLabel lbl_CapNhatTonKho;
    private javax.swing.JLabel lbl_Hinh;
    private javax.swing.JLabel lbl_MaDH;
    private javax.swing.JLabel lbl_NgayDatHang;
    private javax.swing.JLabel lbl_STT;
    private javax.swing.JLabel lbl_TenTK;
    private javax.swing.JLabel lbl_TrangThaiDH;
    private javax.swing.JTable tbl_CTDonDatHang;
    private javax.swing.JTable tbl_SanPham;
    private javax.swing.JTextArea txtA_NhaCC;
    private javax.swing.JTextArea txtA_SanPham;
    private javax.swing.JLabel txt_MaNCC;
    private javax.swing.JTextField txt_MaSP;
    private javax.swing.JLabel txt_NhanVien;
    private javax.swing.JTextField txt_SoLuongSPD;
    private javax.swing.JTextField txt_TenSP;
    private javax.swing.JLabel txt_TongSLSPD;
    // End of variables declaration//GEN-END:variables

}
