/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI_DEAN;

import DAO_DEAN.CTDonDHDAO;
import DAO_DEAN.NhaCCDAO;
import DAO_DEAN.DonDatHangDAO;
import DAO_DEAN.TaiKhoanDAO;
import POJO_DEAN.DonDatHang;
import POJO_DEAN.NhaCC;
import java.awt.Component;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tandat
 */
public class QL_DonDatHang extends javax.swing.JFrame {

    /** Creates new form QL_HoaDon */
    Vector tblDataNhaCC = new Vector();
    Vector tblTitleNhaCC = new Vector();
    Vector tblDataDonHang = new Vector();
    Vector tblTitleDonHang = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<DonDatHang> dsddh = DonDatHangDAO.getDSDDH();
    static ArrayList<NhaCC> dsncc = NhaCCDAO.getDSNCC();
    public QL_DonDatHang() {
        initComponents();
        setLocationRelativeTo(null);
        txtA_NhaCC.setLineWrap(true);
        bangNCC();
        laydulieuNCC(dsncc);
        setCbo_TimKiem();
        setCbo_LoaiSapXep();
        setCbo_SapXep();
        setCbo_TrangThaiDH();
        setCbo_CapNhatTK();
        bangDDH();
        laydulieuDDH(dsddh);
    }

    public void setTenTK(String tenTK){
        lbl_TenTK.setText(tenTK);
    }
    public void bangNCC(){
        tblTitleNhaCC.add("STT"); tblTitleNhaCC.add("Mã khách"); tblTitleNhaCC.add("Họ tên"); 
        tblTitleNhaCC.add("Giới tính"); tblTitleNhaCC.add("Số điện thoại"); 
        tblTitleNhaCC.add("Email"); tblTitleNhaCC.add("Địa chỉ");
    }
    public void laydulieuNCC(ArrayList<NhaCC> dsncc){
        tblDataNhaCC.removeAllElements();
        int j = 0;
        for(NhaCC i : dsncc){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMancc()); v.add(i.getSdtncc()); 
            v.add(i.getHotenncc()); v.add(i.getGioitinhncc());
            v.add(i.getDiachincc()); v.add(i.getSanphamcc());
            tblDataNhaCC.add(v);
            j++;
        }
        tbl_NhaCC.setModel(new DefaultTableModel(tblDataNhaCC, tblTitleNhaCC));
    }
    public void bangDDH(){
        tblTitleDonHang.add("STT"); tblTitleDonHang.add("Mã đơn"); tblTitleDonHang.add("Mã nhà cung cấp"); 
        tblTitleDonHang.add("Nhân viên"); tblTitleDonHang.add("Ngày đặt hàng"); 
        tblTitleDonHang.add("Trạng thái đặt"); tblTitleDonHang.add("Cập nhật tồn kho"); tblTitleDonHang.add("Tổng số lượng sàn phẩm đặt");
    }
    public void laydulieuDDH(ArrayList<DonDatHang> dsddh){
        tblDataDonHang.removeAllElements();
        int j = 0;
        for(DonDatHang i : dsddh){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMaddh()); v.add(i.getMancc()); 
            v.add(i.getNhanvien()); v.add(i.getNgaydh());
            v.add(i.getTrangthaidh()); v.add(i.getCapnhattonkho()); v.add(i.getTongslspdh());
            tblDataDonHang.add(v);
            j++;
        }
        tbl_DonDatHang.setModel(new DefaultTableModel(tblDataDonHang, tblTitleDonHang));
    }
    public void setCbo_TrangThaiDH(){
        String[] x = {"Chưa đặt","Đã đặt"};
        for(String i:x){
            cbo_TrangThaiDH.addItem(i);
        }
    }
    public void setCbo_CapNhatTK(){
        String[] x = {"Chưa cập nhật","Đã cập nhật"};
        for(String i:x){
            cbo_CapNhatTonKho.addItem(i);
        }
    }
    public void setCbo_TimKiem(){
        String[] x = {"Mã đơn","Mã nhà cung cấp","Trạng thái đặt hàng","Cập nhật tồn kho"};
        for(String i:x){
            cbo_TimKiem.addItem(i);
        }
    }
    public void setCbo_LoaiSapXep(){
        String[] x = {"Tăng dần","Giảm dần"};
        for(String i:x){
            cbo_LoaiSapXep.addItem(i);
        }
    }
    public void setCbo_SapXep(){
        String[] x = {"Mã đơn","Mã nhà cung cấp","Tổng số lượng sản phẩm đặt"};
        for(String i:x){
            cbo_SapXep.addItem(i);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_TimKiem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbo_TimKiem = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbo_SapXep = new javax.swing.JComboBox<>();
        btn_SapXep = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbo_LoaiSapXep = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_ChiTiet = new javax.swing.JButton();
        btn_DatHang = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_STT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_MaDon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_MaNCC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_NgayDatHang = new javax.swing.JLabel();
        cbo_TrangThaiDH = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbo_CapNhatTonKho = new javax.swing.JComboBox<>();
        txt_NhanVien = new javax.swing.JLabel();
        txt_TongSLSPD = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_TenTK = new javax.swing.JLabel();
        lbl_BangHD1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_DonDatHang = new javax.swing.JTable();
        lbl_BangHD = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_NhaCC = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_NhaCC = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ĐƠN ĐẶT HÀNG");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        btn_TimKiem.setBackground(new java.awt.Color(255, 0, 102));
        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TimKiem.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tìm kiếm theo :");

        cbo_TimKiem.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_TimKiem))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(cbo_TimKiem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn_TimKiem)
                .addGap(27, 27, 27))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Sắp xếp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Sắp xếp theo :");

        cbo_SapXep.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        btn_SapXep.setBackground(new java.awt.Color(255, 0, 102));
        btn_SapXep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_SapXep.setForeground(new java.awt.Color(255, 255, 255));
        btn_SapXep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/SapXep.png"))); // NOI18N
        btn_SapXep.setText("Sắp xếp");
        btn_SapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SapXepActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Sắp xếp :");

        cbo_LoaiSapXep.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_LoaiSapXep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbo_SapXep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbo_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_LoaiSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_SapXep)
                .addGap(23, 23, 23))
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 7, 2, 6));

        btn_Them.setBackground(new java.awt.Color(255, 0, 102));
        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Them.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Them);

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 102));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Xoa.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Xoa);

        btn_Sua.setBackground(new java.awt.Color(255, 0, 102));
        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sua.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sua);

        btn_ChiTiet.setBackground(new java.awt.Color(255, 0, 102));
        btn_ChiTiet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/XemChiTiet.png"))); // NOI18N
        btn_ChiTiet.setText("Xem chi tiết");
        btn_ChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChiTietActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ChiTiet);

        btn_DatHang.setBackground(new java.awt.Color(255, 0, 102));
        btn_DatHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_DatHang.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order.png"))); // NOI18N
        btn_DatHang.setText("Đặt hàng");
        btn_DatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatHangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_DatHang);

        btn_LamMoi.setBackground(new java.awt.Color(255, 0, 102));
        btn_LamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LamMoi.png"))); // NOI18N
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LamMoi);

        btn_Thoat.setBackground(new java.awt.Color(255, 0, 102));
        btn_Thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Thoat.png"))); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Thoat);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Thông tin đơn đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Số thứ tự");

        lbl_STT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_STT.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mã đơn");

        txt_MaDon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Mã nhà cung cấp");

        txt_MaNCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Tổng số lượng sản phẩm đặt");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Ngày đặt hàng");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Trạng thái đặt hàng");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Cập nhật tồn kho");

        lbl_NgayDatHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cbo_TrangThaiDH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Nhân viên");

        cbo_CapNhatTonKho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_NhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txt_TongSLSPD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(cbo_CapNhatTonKho, 0, 273, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbo_TrangThaiDH, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_MaNCC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TongSLSPD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_NgayDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lbl_STT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(txt_MaDon)))
                .addGap(12, 12, 12))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(txt_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(lbl_STT, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(7, 7, 7))
                    .addComponent(txt_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_TongSLSPD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NgayDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbo_TrangThaiDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbo_CapNhatTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        lbl_1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 51, 102));
        lbl_1.setText("Tài khoản :");

        lbl_TenTK.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_TenTK.setForeground(new java.awt.Color(255, 51, 102));

        lbl_BangHD1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Bảng đơn đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        tbl_DonDatHang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_DonDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_DonDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DonDatHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_DonDatHang);

        javax.swing.GroupLayout lbl_BangHD1Layout = new javax.swing.GroupLayout(lbl_BangHD1);
        lbl_BangHD1.setLayout(lbl_BangHD1Layout);
        lbl_BangHD1Layout.setHorizontalGroup(
            lbl_BangHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
        );
        lbl_BangHD1Layout.setVerticalGroup(
            lbl_BangHD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );

        lbl_BangHD.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Bảng nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        tbl_NhaCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_NhaCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_NhaCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhaCCMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_NhaCC);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)), "Thông tin nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtA_NhaCC.setColumns(20);
        txtA_NhaCC.setRows(5);
        jScrollPane1.setViewportView(txtA_NhaCC);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout lbl_BangHDLayout = new javax.swing.GroupLayout(lbl_BangHD);
        lbl_BangHD.setLayout(lbl_BangHDLayout);
        lbl_BangHDLayout.setHorizontalGroup(
            lbl_BangHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_BangHDLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbl_BangHDLayout.setVerticalGroup(
            lbl_BangHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(286, 286, 286)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_BangHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_BangHD1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_BangHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_BangHD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_NhaCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhaCCMouseClicked
        // TODO add your handling code here:
        String STT = tbl_NhaCC.getValueAt(tbl_NhaCC.getSelectedRow(), 0).toString();
        String maso = tbl_NhaCC.getValueAt(tbl_NhaCC.getSelectedRow(), 1).toString();
        String sdt = tbl_NhaCC.getValueAt(tbl_NhaCC.getSelectedRow(), 2).toString();
        String hoten = tbl_NhaCC.getValueAt(tbl_NhaCC.getSelectedRow(), 3).toString();
        String gt = tbl_NhaCC.getValueAt(tbl_NhaCC.getSelectedRow(), 4).toString();
        String diachi = tbl_NhaCC.getValueAt(tbl_NhaCC.getSelectedRow(), 5).toString();
        String spcc = tbl_NhaCC.getValueAt(tbl_NhaCC.getSelectedRow(), 6).toString();

        
        txt_MaNCC.setText(maso);
        txtA_NhaCC.setText("STT: "+STT+"\n\nMã số: "+maso+"\n\nSố điện thoại: "
                +sdt+"\n\nHọ tên: "+hoten+"\n\nGiới tính: "+gt+"\n\nĐịa chỉ: "+diachi+"\n\nSản phẩm cung cấp:\n"+spcc);
            
    }//GEN-LAST:event_tbl_NhaCCMouseClicked

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        //        {"Mã đơn","Mã nhà cung cấp","Trạng thái đặt hàng","Cập nhật tồn kho"}
        String obj = "";
        String value = "";
        if(cbo_TimKiem.getSelectedIndex()==0){
            obj = "MaDonDH";
            value = txt_MaDon.getText().trim();
        }else if(cbo_TimKiem.getSelectedIndex()==1){
            obj = "MaNCC";
            value = txt_MaNCC.getText().trim();
        }else if(cbo_TimKiem.getSelectedIndex()==2){
            obj = "TrangThaiDH";
            value = cbo_TrangThaiDH.getSelectedItem().toString().trim();
        }else{
            obj = "CapNhatTonKho";
            value = cbo_CapNhatTonKho.getSelectedItem().toString().trim();
        }
        ArrayList<DonDatHang> ResultSearch= new  ArrayList<DonDatHang>();
        ResultSearch = DonDatHangDAO.TimKiem(obj,value);
        laydulieuDDH(ResultSearch);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_SapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SapXepActionPerformed
        // TODO add your handling code here:
        //        {"Mã đơn","Mã nhà cung cấp","Tổng số lượng sản phẩm đặt"};
        String obj = "";
        if(cbo_SapXep.getSelectedIndex()==0)
            obj = "MaDonDH";
        else if(cbo_SapXep.getSelectedIndex()==1)
            obj = "MaNCC";
        else
            obj = "TongSLSPD";
        String StyleSort = "";
        if(cbo_LoaiSapXep.getSelectedIndex()==0)
            StyleSort = "asc";
        else
            StyleSort = "desc";
        ArrayList<DonDatHang> ResultSort= new  ArrayList<DonDatHang>();
        ResultSort = DonDatHangDAO.SapXep(obj,StyleSort);
        laydulieuDDH(ResultSort);
    }//GEN-LAST:event_btn_SapXepActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        if(txt_MaDon.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Mã đơn không được để trống !","Thông báo",2);
        else
        {
            if(tbl_DonDatHang.getSelectedRowCount()==1)
            {
                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    String maddh = txt_MaDon.getText().trim();
                    String sql = "delete CTDonDatHang where MaDonDH = '"+maddh+"'\n"+
                            "delete DonDatHang where MaDonDH = '"+maddh+"'";
                    if(DonDatHangDAO.ThemXoaSua(sql)!=-1)
                    {
                        clearAllTextField(this.getContentPane());
                        returnDefaultAllCbo(this.getContentPane());
                        dsddh = DonDatHangDAO.getDSDDH();
                        laydulieuDDH(dsddh);
                        JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                    }
                    else
                        JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);

                }
            }else{
                if(tbl_DonDatHang.getRowCount()==0)
                    JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
                else
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChiTietActionPerformed
        // TODO add your handling code here:
        String madh= txt_MaDon.getText().trim();
        String mancc = txt_MaNCC.getText().trim();
        String nv = txt_NhanVien.getText().trim();
        String tongslsp = txt_TongSLSPD.getText().trim();
        String ngaydh = lbl_NgayDatHang.getText().trim();
        String trangthaidh = cbo_TrangThaiDH.getSelectedItem().toString();
        String capnhattonkho = cbo_CapNhatTonKho.getSelectedItem().toString();
        
        if(madh.equals("") || mancc.equals(""))
            JOptionPane.showMessageDialog(this, "Chưa chọn mã đơn đặt hàng và mã nhà cung cấp cần xem !","Thông báo",2);
        else
        {
            close();
            QL_CTDonDatHang ctddh = new QL_CTDonDatHang();
            ctddh.ThongTinDDH(madh,mancc,nv,tongslsp,ngaydh,trangthaidh,capnhattonkho);
            ctddh.setTenTK(lbl_TenTK.getText());
            ctddh.setVisible(true);
        }
    }//GEN-LAST:event_btn_ChiTietActionPerformed

    public void returnDefaultAllCbo(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JComboBox){
                JComboBox f = (JComboBox)c;
                f.setSelectedIndex(0);
            }
            else if(c instanceof Container)
                returnDefaultAllCbo((Container)c);
        }
    }
    public void clearAllTextField(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JTextField){
                JTextField f = (JTextField)c;
                f.setText("");
            }
            else if(c instanceof Container)
                clearAllTextField((Container)c);
        }
    }
    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        returnDefaultAllCbo(this.getContentPane());
        clearAllTextField(this.getContentPane());
        lbl_STT.setText("");
        lbl_NgayDatHang.setText("");
        txt_NhanVien.setText("");
        txt_TongSLSPD.setText("");
        laydulieuDDH(dsddh);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        close();
        FormGiaoDien frmggd = new FormGiaoDien();
        frmggd.setTenTK(lbl_TenTK.getText());
        frmggd.setVisible(true);
    }//GEN-LAST:event_btn_ThoatActionPerformed

    public Boolean KiemTraTXT(){
        String mancc = txt_MaNCC.getText().trim();
        String madon = txt_MaDon.getText().trim();
        
        if(mancc.equals("")){
            JOptionPane.showMessageDialog(this, "Mã nhà cung cấp không được để trống !", "Thông báo", 2);
            return false;
        }
        if(mancc.length()<=3)
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã nhà cung cấp là NCCxxx với x là số", "Thông báo", 2);
            return false;
        }
        
        String dauMaNCC = mancc.substring(0,3);
        if(dauMaNCC.equals("NCC") == false){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã nhà cung cấp là NCCxxx với x là số", "Thông báo", 2);
            return false;
        }
        try {
            int duoimMaNCC = Integer.parseInt(mancc.substring(3));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã nhà cung cấp là NCCxxx với x là số", "Thông báo", 2);
            return false;
        }
        
        if(madon.equals("")){
            JOptionPane.showMessageDialog(this, "mã đơn không được để trống !", "Thông báo", 2);
            return false;
        }
        if(madon.length()<=3){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã đơn là DDHxxx với x là số","Thông báo",2);
            return false;
        }
        String dauMaDDH = madon.substring(0,3);
        if(dauMaDDH.equals("DDH") == false){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã đơn là DDHxxx với x là số", "Thông báo", 2);
            return false;
        }
        try {
            int duoiMaDDH = Integer.parseInt(madon.substring(3));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã đơn là DDHxxx với x là số", "Thông báo", 2);
            return false;
        }
        
        
        return true;
    }
    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        String madon = txt_MaDon.getText().trim();
        String mancc = txt_MaNCC.getText().trim();
        if(KiemTraTXT()){
            if(tbl_DonDatHang.getSelectedRowCount()==1)
            {
                String trangthaidh = DonDatHangDAO.XuatTTDatHang(madon);
                if(trangthaidh.equals("Chưa đặt")){
                    if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

                                String sql = "update DonDatHang\n" +
                                "set MaNCC='"+mancc+"'\n" +
                                "where MaDonDH = '"+madon+"'";
                                DonDatHangDAO.ThemXoaSua(sql);
                                dsddh = DonDatHangDAO.getDSDDH();
                                laydulieuDDH(dsddh);
                                JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
                    }else{
                        if(tbl_DonDatHang.getRowCount()==0)
                            JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
                        else
                            JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Đơn đặt hàng này đã đặt không thể sửa","Thông báo",2);
                }
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void tbl_DonDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DonDatHangMouseClicked
        // TODO add your handling code here:
        String STT = tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 0).toString();
        String madon = tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 1).toString();
        String mancc = tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 2).toString();
        String nhanvien = tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 3).toString();
        String TrangThaiDH = tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 5).toString();
        String CapNhatTonKho = tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 6).toString();
        String TongSLSPD = tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 7).toString();

        lbl_STT.setText(STT);
        txt_MaDon.setText(madon);
        txt_MaNCC.setText(mancc);
        txt_NhanVien.setText(nhanvien);
        txt_TongSLSPD.setText(TongSLSPD);
        String tg = "";
        if(tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 4)!=null)
            tg = tbl_DonDatHang.getValueAt(tbl_DonDatHang.getSelectedRow(), 4).toString();
        else
            tg = "";
        
        lbl_NgayDatHang.setText(tg);
        if(TrangThaiDH.equals(cbo_TrangThaiDH.getItemAt(0)))
            cbo_TrangThaiDH.setSelectedIndex(0);
        else
            cbo_TrangThaiDH.setSelectedIndex(1);
        
        if(CapNhatTonKho.equals(cbo_CapNhatTonKho.getItemAt(0)))
            cbo_CapNhatTonKho.setSelectedIndex(0);
        else
            cbo_CapNhatTonKho.setSelectedIndex(1);
    }//GEN-LAST:event_tbl_DonDatHangMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        String madon = txt_MaDon.getText().trim();
        String mancc = txt_MaNCC.getText().trim();
        String tk = lbl_TenTK.getText().trim();
        String quyen = TaiKhoanDAO.XuatQuyen(tk);
        if(KiemTraTXT()){
            if(quyen.equals("Admin"))
                JOptionPane.showMessageDialog(this, "Admin không thể thêm !", "Thông báo", 2);
            else{
                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không ?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                            String tentk = lbl_TenTK.getText().trim();
                            String manv = TaiKhoanDAO.XuatMaNV(tentk);

                            String sql = "insert into DonDatHang(MaDonDH,MaNCC,MaNV) values('"+madon+"','"+mancc+"','"+manv+"')";
                            int kq=DonDatHangDAO.ThemXoaSua(sql);
                            if(kq!=-1)
                            {
                                dsddh = DonDatHangDAO.getDSDDH();
                                laydulieuDDH(dsddh);
                                JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
                            }
                            else
                                 JOptionPane.showMessageDialog(this, "Mã đơn hàng đã tồn tại !", "Thông báo", 2);

                        }
            }
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_DatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatHangActionPerformed
        // TODO add your handling code here:
        String madon = txt_MaDon.getText().trim();
        if(madon.equals("")){
            JOptionPane.showMessageDialog(this, "Mã đơn đặt hàng không được để trống !", "Thông báo", 2);
        }else{
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đặt hàng không ?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){

                int slsp = DonDatHangDAO.XuatTongSLSPDat(madon);
                if(slsp==0)
                    JOptionPane.showMessageDialog(this, "Chưa có sản phẩm trong đơn hàng !", "Thông báo",2);
                else{
                    String trangthaidh = DonDatHangDAO.XuatTTDatHang(madon);
                    if(trangthaidh.equals("Chưa đặt")){
                                String sql = "update DonDatHang set NgayDH = GETDATE() where MaDonDH = '"+madon+"'\n"+
                                             "update DonDatHang set TrangThaiDH = N'Đã đặt' where MaDonDH = '"+madon+"'";
                                int kq=DonDatHangDAO.ThemXoaSua(sql);
                                if(kq!=-1)
                                {
                                    dsddh = DonDatHangDAO.getDSDDH();
                                    laydulieuDDH(dsddh);
                                    JOptionPane.showMessageDialog(this, "Đặt hàng thành công !", "Thông báo",1);
                                    String ngaydh = DonDatHangDAO.XuatNgayDatHang(madon);
                                    lbl_NgayDatHang.setText(ngaydh);
                                }
                    }else
                        JOptionPane.showMessageDialog(this, "Đơn đặt hàng đã đặt rồi !", "Thông báo", 2);
                }
            }
        }
    }//GEN-LAST:event_btn_DatHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_DonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_DonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_DonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_DonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_DonDatHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChiTiet;
    private javax.swing.JButton btn_DatHang;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_SapXep;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbo_CapNhatTonKho;
    private javax.swing.JComboBox<String> cbo_LoaiSapXep;
    private javax.swing.JComboBox<String> cbo_SapXep;
    private javax.swing.JComboBox<String> cbo_TimKiem;
    private javax.swing.JComboBox<String> cbo_TrangThaiDH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JPanel lbl_BangHD;
    private javax.swing.JPanel lbl_BangHD1;
    private javax.swing.JLabel lbl_NgayDatHang;
    private javax.swing.JLabel lbl_STT;
    private javax.swing.JLabel lbl_TenTK;
    private javax.swing.JTable tbl_DonDatHang;
    private javax.swing.JTable tbl_NhaCC;
    private javax.swing.JTextArea txtA_NhaCC;
    private javax.swing.JTextField txt_MaDon;
    private javax.swing.JTextField txt_MaNCC;
    private javax.swing.JLabel txt_NhanVien;
    private javax.swing.JLabel txt_TongSLSPD;
    // End of variables declaration//GEN-END:variables

}
