/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI_DEAN;

import DAO_DEAN.CTHoaDonDAO;
import DAO_DEAN.HoaDonDAO;
import POJO_DEAN.HoaDon;
import java.awt.Component;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tandat
 */
public class QL_HoaDon extends javax.swing.JFrame {

    /** Creates new form QL_HoaDon */
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<HoaDon> dshd = HoaDonDAO.getDSHD();
    public QL_HoaDon() {
        
        initComponents();
        setLocationRelativeTo(null);
        bangHD();
        laydulieuHD(dshd);
        setCbo_TrangThai();
        setCbo_TimKiem();
        setCbo_LoaiSapXep();
        setCbo_SapXep();
        setCbo_LoaiGG();
    }

    public void setTenTK(String tenTK){
        lbl_TenTK.setText(tenTK);
    }
    public void bangHD(){
        tblTitle.add("STT"); tblTitle.add("Mã hóa đơn"); tblTitle.add("Tổng số lượng"); 
        tblTitle.add("Tổng tiền"); tblTitle.add("Giảm giá"); 
        tblTitle.add("Thành tiền"); tblTitle.add("Trạng thái"); tblTitle.add("Thời gian");
    }
    public void laydulieuHD(ArrayList<HoaDon> dshd){
        tblData.removeAllElements();
        int j = 0;
        for(HoaDon i : dshd){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMahd()); 
            v.add(i.getTongsl()); v.add(i.getTongtienhd());
            v.add(i.getGiamgia()); v.add(i.getThanhtien()); 
            v.add(i.getTrangthai()); v.add(i.getTg());
            tblData.add(v);
            j++;
        }
        tbl_HoaDon.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    public void setCbo_LoaiGG(){
        String[] x = {"Đ","%"};
        for(String i:x){
            cbo_LoaiGG.addItem(i);
        }
    }
    public void setCbo_TrangThai(){
        String[] x = {"Chưa thanh toán","Đã thanh toán"};
        for(String i:x){
            cbo_TrangThai.addItem(i);
        }
    }
    public void setCbo_TimKiem(){
        String[] x = {"Mã hóa đơn","Trạng thái"};
        for(String i:x){
            cbo_TimKiem.addItem(i);
        }
    }
    public void setCbo_LoaiSapXep(){
        String[] x = {"Tăng dần","Giảm dần"};
        for(String i:x){
            cbo_LoaiSapXep.addItem(i);
        }
    }
    public void setCbo_SapXep(){
        String[] x = {"Mã hóa đơn","Tổng số lượng","Thành tiền"};
        for(String i:x){
            cbo_SapXep.addItem(i);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_BangHD = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btn_TimKiem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbo_TimKiem = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbo_SapXep = new javax.swing.JComboBox<>();
        btn_SapXep = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbo_LoaiSapXep = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btn_Xoa = new javax.swing.JButton();
        btn_ChiTiet = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_InHD = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_STT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_TongSL = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_GiamGia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_ThanhTien = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbo_TrangThai = new javax.swing.JComboBox<>();
        cbo_LoaiGG = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_TG = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_TenTK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN");

        lbl_BangHD.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Bảng hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        tbl_HoaDon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_HoaDon);

        javax.swing.GroupLayout lbl_BangHDLayout = new javax.swing.GroupLayout(lbl_BangHD);
        lbl_BangHD.setLayout(lbl_BangHDLayout);
        lbl_BangHDLayout.setHorizontalGroup(
            lbl_BangHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        lbl_BangHDLayout.setVerticalGroup(
            lbl_BangHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        btn_TimKiem.setBackground(new java.awt.Color(255, 0, 102));
        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TimKiem.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tìm kiếm theo :");

        cbo_TimKiem.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_TimKiem))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btn_TimKiem)
                .addGap(27, 27, 27))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Sắp xếp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Sắp xếp theo :");

        cbo_SapXep.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        btn_SapXep.setBackground(new java.awt.Color(255, 0, 102));
        btn_SapXep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_SapXep.setForeground(new java.awt.Color(255, 255, 255));
        btn_SapXep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/SapXep.png"))); // NOI18N
        btn_SapXep.setText("Sắp xếp");
        btn_SapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SapXepActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Sắp xếp :");

        cbo_LoaiSapXep.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_LoaiSapXep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbo_SapXep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbo_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_LoaiSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_SapXep)
                .addGap(23, 23, 23))
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 5, 2, 6));

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 102));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Xoa.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Xoa);

        btn_ChiTiet.setBackground(new java.awt.Color(255, 0, 102));
        btn_ChiTiet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/XemChiTiet.png"))); // NOI18N
        btn_ChiTiet.setText("Xem chi tiết");
        btn_ChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChiTietActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ChiTiet);

        btn_LamMoi.setBackground(new java.awt.Color(255, 0, 102));
        btn_LamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LamMoi.png"))); // NOI18N
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LamMoi);

        btn_InHD.setBackground(new java.awt.Color(255, 0, 102));
        btn_InHD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_InHD.setForeground(new java.awt.Color(255, 255, 255));
        btn_InHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/InHoaDon.png"))); // NOI18N
        btn_InHD.setText("In hóa đơn");
        btn_InHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InHDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_InHD);

        btn_Thoat.setBackground(new java.awt.Color(255, 0, 102));
        btn_Thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Thoat.png"))); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Thoat);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Thông tin tài khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Số thứ tự");

        lbl_STT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_STT.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mã hóa đơn");

        txt_MaHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Tổng số lượng");

        txt_TongSL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Tổng tiền");

        txt_TongTien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_TongTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Giảm giá");

        txt_GiamGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_GiamGia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Thành tiền");

        txt_ThanhTien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ThanhTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Trạng thái");

        cbo_TrangThai.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        cbo_LoaiGG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Đ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Thời gian");

        lbl_TG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_TG.setForeground(new java.awt.Color(255, 0, 0));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Đ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_STT, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(txt_TongSL, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txt_GiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbo_LoaiGG, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txt_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbo_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_TG, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel16)
                    .addComponent(jLabel3))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(lbl_STT, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_TongSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_GiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbo_LoaiGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lbl_TG, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 51, 102));
        lbl_1.setText("Tài khoản :");

        lbl_TenTK.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_TenTK.setForeground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_BangHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_BangHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonMouseClicked
        // TODO add your handling code here:
        String STT = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 0).toString();
        String mahd = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 1).toString();
        String tongsl = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 2).toString();
        String tongtien = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 3).toString();
        String giamgia = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 4).toString();
        String thanhtien = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 5).toString();
        String trangthai = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 6).toString();
        String tg = "";
        if(tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 7)!=null)
            tg = tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 7).toString();
        else
            tg = "";
        String loaigg = HoaDonDAO.LoaiGG(mahd); 
        
        lbl_TG.setText(tg);
            
        lbl_STT.setText(STT);
        txt_MaHD.setText(mahd);
        txt_TongSL.setText(tongsl);
        txt_TongTien.setText(tongtien);
        txt_GiamGia.setText(giamgia);
        txt_ThanhTien.setText(thanhtien);
        
        if(trangthai.equals(cbo_TrangThai.getItemAt(0)))
            cbo_TrangThai.setSelectedIndex(0);
        else
            cbo_TrangThai.setSelectedIndex(1);
        
        if(loaigg.equals(cbo_LoaiGG.getItemAt(0)))
            cbo_LoaiGG.setSelectedIndex(0);
        else
            cbo_LoaiGG.setSelectedIndex(1);
            
    }//GEN-LAST:event_tbl_HoaDonMouseClicked

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        //        {"Mã hóa đơn","Trạng thái"}
        String obj = "";
        String value = "";
        if(cbo_TimKiem.getSelectedIndex()==0){
            obj = "MaHD";
            value = txt_MaHD.getText().trim();
        }else{
            obj = "TrangThai";
            value = cbo_TrangThai.getSelectedItem().toString().trim();
        }
        ArrayList<HoaDon> ResultSearch= new  ArrayList<HoaDon>();
        ResultSearch = HoaDonDAO.TimKiem(obj,value);
        laydulieuHD(ResultSearch);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_SapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SapXepActionPerformed
        // TODO add your handling code here:
        //        {"Mã hóa đơn","Tổng số lượng","Thành tiền"}
        String obj = "";
        if(cbo_SapXep.getSelectedIndex()==0)
            obj = "MaHD";
        else if(cbo_SapXep.getSelectedIndex()==1)
            obj = "TongSL";
        else
            obj = "ThanhTien";
        String StyleSort = "";
        if(cbo_LoaiSapXep.getSelectedIndex()==0)
            StyleSort = "asc";
        else
            StyleSort = "desc";
        ArrayList<HoaDon> ResultSort= new  ArrayList<HoaDon>();
        ResultSort = HoaDonDAO.SapXep(obj,StyleSort);
        laydulieuHD(ResultSort);
    }//GEN-LAST:event_btn_SapXepActionPerformed

    public void CapNhatToanBoSL_SP(String mahd){
        ArrayList<String> dsmsp = CTHoaDonDAO.XuatMaSP_HD(mahd);
        for(String i:dsmsp){
            
            int soluongsp = CTHoaDonDAO.XuatSL_MaCTHD(mahd, i);
            
            String sql_CapNhatSL = "exec CapNhatSLSP_XoaHD '"+i+"',"+soluongsp+"";
            HoaDonDAO.ThemXoaSua(sql_CapNhatSL);
        }
    }
    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        if(txt_MaHD.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Mã hóa đơn không được để trống !","Thông báo",2);
        else
        {
            if(tbl_HoaDon.getSelectedRowCount()==1)
            {
                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    String mahd = txt_MaHD.getText().trim();
                    CapNhatToanBoSL_SP(mahd);
                    String sql = "delete CTHD where MaCTHD = '"+mahd+"'\n"+
                            "delete HoaDon where MaHD = '"+mahd+"'";
                    if(HoaDonDAO.ThemXoaSua(sql)!=-1)
                    {
                        clearAllTextField(this.getContentPane());
                        returnDefaultAllCbo(this.getContentPane());
                        dshd = HoaDonDAO.getDSHD();
                        laydulieuHD(dshd);
                        JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                    }
                    else
                        JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);

                }
            }else{
                if(tbl_HoaDon.getRowCount()==0)
                    JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
                else
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChiTietActionPerformed
        // TODO add your handling code here:
        String mahd = txt_MaHD.getText().trim();
        if(mahd.equals(""))
            JOptionPane.showMessageDialog(this, "Chưa chọn mã hóa đơn cần xem !","Thông báo",2);
        else
        {
            close();
            QL_CTHD cthd = new QL_CTHD();
            cthd.ThongTinHD(mahd);
            cthd.setTenTK(lbl_TenTK.getText());
            cthd.setVisible(true);
        }
    }//GEN-LAST:event_btn_ChiTietActionPerformed

    public void returnDefaultAllCbo(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JComboBox){
                JComboBox f = (JComboBox)c;
                f.setSelectedIndex(0);
            }
            else if(c instanceof Container)
                returnDefaultAllCbo((Container)c);
        }
    }
    public void clearAllTextField(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JTextField){
                JTextField f = (JTextField)c;
                f.setText("");
            }
            else if(c instanceof Container)
                clearAllTextField((Container)c);
        }
    }
    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        returnDefaultAllCbo(this.getContentPane());
        clearAllTextField(this.getContentPane());
        laydulieuHD(dshd);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        close();
        FormGiaoDien frmggd = new FormGiaoDien();
        frmggd.setTenTK(lbl_TenTK.getText());
        frmggd.setVisible(true);
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_InHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InHDActionPerformed
        // TODO add your handling code here:
        if(!txt_MaHD.equals("")){
            if(cbo_TrangThai.getSelectedItem().toString()=="Đã thanh toán"){
                XuatHD XHD = new XuatHD();
                XHD.ThongTinHD(txt_MaHD.getText().trim());
                XHD.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Không thể in vì hóa đơn này chưa thanh toán !","Thông báo",2);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa chọn hóa đơn cần in !","Thông báo",2);
    }//GEN-LAST:event_btn_InHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_HoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChiTiet;
    private javax.swing.JButton btn_InHD;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_SapXep;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbo_LoaiGG;
    private javax.swing.JComboBox<String> cbo_LoaiSapXep;
    private javax.swing.JComboBox<String> cbo_SapXep;
    private javax.swing.JComboBox<String> cbo_TimKiem;
    private javax.swing.JComboBox<String> cbo_TrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JPanel lbl_BangHD;
    private javax.swing.JLabel lbl_STT;
    private javax.swing.JLabel lbl_TG;
    private javax.swing.JLabel lbl_TenTK;
    private javax.swing.JTable tbl_HoaDon;
    private javax.swing.JTextField txt_GiamGia;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_ThanhTien;
    private javax.swing.JTextField txt_TongSL;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables

}
