/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_DEAN;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import DAO_DEAN.NhanVienDAO;
import POJO_DEAN.NhanVien;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sun.security.util.Length;

/**
 *
 * @author tandat
 */
public class QL_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QL_KhachHang
     */
    
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<NhanVien> dsnv = NhanVienDAO.getDSNV();
    public QL_NhanVien() {
        
        initComponents();
         setLocationRelativeTo(null);
        bangNV();
        laydulieuNV(dsnv);
        txtA_DiaChi.setLineWrap(true);
        setCbo_GT();
        setCbo_LoaiSapXep();
        setCbo_SapXep();
        setCbo_TimKiem();
    }

    public void setTenTK(String tenTK){
        lbl_TenTK.setText(tenTK);
    }
    public void bangNV(){
        tblTitle.add("STT"); tblTitle.add("Mã"); tblTitle.add("Họ tên"); 
        tblTitle.add("Giới tính"); tblTitle.add("Số điện thoại"); 
        tblTitle.add("Số CCCD"); tblTitle.add("Ngày sinh");
        tblTitle.add("Địa chỉ"); tblTitle.add("Quê quán");
    }
    public void laydulieuNV(ArrayList<NhanVien> dsnv){
        tblData.removeAllElements();
        int j = 0;
        for(NhanVien i : dsnv){
            Vector v = new Vector();
            v.add(j+1); v.add(i.getMa()); 
            v.add(i.getHoten()); v.add(i.getGioitinh());
            v.add(i.getSdt()); v.add(i.getSocccd()); 
            v.add(i.getNgaysinh()); v.add(i.getDiachi()); 
            v.add(i.getQuequan());
            tblData.add(v);
            j++;
        }
        tbl_NhanVien.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    public void setCbo_GT(){
        String[] x = {"Nam","Nữ"};
        for(String i:x){
            cbo_GT.addItem(i);
        }
    }
    public void setCbo_TimKiem(){
        String[] x = {"Mã số","Họ tên","Giới tính","Số điện thoại","Số CCCD","Quê quán"};
        for(String i:x){
            cbo_TimKiem.addItem(i);
        }
    }
    public void setCbo_LoaiSapXep(){
        String[] x = {"Tăng dần","Giảm dần"};
        for(String i:x){
            cbo_LoaiSapXep.addItem(i);
        }
    }
    public void setCbo_SapXep(){
        String[] x = {"Mã số","Họ tên","Số điện thoại","Số CCCD"};
        for(String i:x){
            cbo_SapXep.addItem(i);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_TimKiem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbo_TimKiem = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_HoTen = new javax.swing.JTextField();
        lbl_STT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_DiaChi = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        cbo_GT = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_SoCCCD = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_NgaySinh = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_QueQuan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_HinhAnh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_Browser = new javax.swing.JTextField();
        btn_LinkAnh = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbo_SapXep = new javax.swing.JComboBox<>();
        btn_SapXep = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbo_LoaiSapXep = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_NhanVien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        lbl_1 = new javax.swing.JLabel();
        lbl_TenTK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        btn_TimKiem.setBackground(new java.awt.Color(255, 0, 102));
        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TimKiem.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tìm kiếm theo :");

        cbo_TimKiem.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_TimKiem))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(btn_TimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Số thứ tự");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Họ tên");

        txt_HoTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_STT.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_STT.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Số điện thoại");

        txt_SDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SDTKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Địa chỉ");

        txtA_DiaChi.setColumns(20);
        txtA_DiaChi.setRows(5);
        jScrollPane1.setViewportView(txtA_DiaChi);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Giới tính");

        cbo_GT.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mã số");

        txt_MaNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Số CCCD");

        txt_SoCCCD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_SoCCCD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SoCCCDKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Ngày sinh");

        txt_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_NgaySinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NgaySinhKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Quê quán");

        txt_QueQuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Hình ảnh", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12))); // NOI18N

        lbl_HinhAnh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_HinhAnh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_HinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Browser");

        txt_Browser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_LinkAnh.setBackground(new java.awt.Color(255, 0, 102));
        btn_LinkAnh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_LinkAnh.setForeground(new java.awt.Color(255, 255, 255));
        btn_LinkAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Browser.png"))); // NOI18N
        btn_LinkAnh.setText("Browser");
        btn_LinkAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LinkAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(lbl_STT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_MaNV)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(6, 6, 6))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(txt_SoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addComponent(txt_QueQuan)))
                        .addGap(119, 119, 119)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_LinkAnh)
                        .addGap(2, 2, 2))
                    .addComponent(txt_Browser, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(txt_HoTen)
                    .addComponent(cbo_GT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_STT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_SoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Browser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_QueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btn_LinkAnh)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Sắp xếp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Sắp xếp theo :");

        cbo_SapXep.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        btn_SapXep.setBackground(new java.awt.Color(255, 0, 102));
        btn_SapXep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_SapXep.setForeground(new java.awt.Color(255, 255, 255));
        btn_SapXep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/SapXep.png"))); // NOI18N
        btn_SapXep.setText("Sắp xếp");
        btn_SapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SapXepActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Sắp xếp :");

        cbo_LoaiSapXep.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_LoaiSapXep, 0, 246, Short.MAX_VALUE)
                    .addComponent(cbo_SapXep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbo_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_LoaiSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_SapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Bảng nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        tbl_NhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_NhanVien);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 5, 2, 6));

        btn_Them.setBackground(new java.awt.Color(255, 0, 102));
        btn_Them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Them.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Them);

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 102));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Xoa.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Xoa);

        btn_Sua.setBackground(new java.awt.Color(255, 0, 102));
        btn_Sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sua.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sua);

        btn_LamMoi.setBackground(new java.awt.Color(255, 0, 102));
        btn_LamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LamMoi.png"))); // NOI18N
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LamMoi);

        btn_Thoat.setBackground(new java.awt.Color(255, 0, 102));
        btn_Thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Thoat.png"))); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Thoat);

        lbl_1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 51, 102));
        lbl_1.setText("Tài khoản :");

        lbl_TenTK.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_TenTK.setForeground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(117, 117, 117)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Boolean KiemTraTXT(){
        String hoten = txt_HoTen.getText().trim();
        String sdt = txt_SDT.getText().trim();
        String diachi = txtA_DiaChi.getText().trim();
        String manv = txt_MaNV.getText().trim();
        String socccd = txt_SoCCCD.getText().trim();
        String ngaysinh = txt_NgaySinh.getText().trim();
        String quequan = txt_QueQuan.getText().trim();
        String hinh = txt_Browser.getText().trim();
        
        
        if(manv.equals("") || diachi.equals("")|| socccd.equals("")|| ngaysinh.equals("")|| quequan.equals("") || sdt.equals("") || hoten.equals("") || hinh.equals("")){
            JOptionPane.showMessageDialog(this, "Thông tin nhân viên không được để trống !", "Thông báo", 2);
            return false;
        }
        
        if(manv.length()<=2)
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã nhân viên là NVxxx với x là số", "Thông báo", 2);
            return false;
        }
        
        String dauMaNV = manv.substring(0,2);
        if(dauMaNV.equals("NV") == false){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã nhân viên là NVxxx với x là số", "Thông báo", 2);
            return false;
        }
        try {
            int duoimMaNV = Integer.parseInt(manv.substring(2));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng mã nhân viên là NVxxx với x là số", "Thông báo", 2);
            return false;
        }
        
        if(sdt.length()<10 || sdt.length()>10){
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ !","Thông báo",2);
            return false;
        }
        String dauSDT = sdt.substring(0,1);
        if(!dauSDT.equals("0")){
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ !","Thông báo",2);
            return false;
        }
        
        
        
        if(socccd.length()<12 || socccd.length()>12){
            JOptionPane.showMessageDialog(this, "Số CCCD không hợp lệ !","Thông báo",2);
            return false;
        }
        String dauCCCD = socccd.substring(0,1);
        if(!dauCCCD.equals("0")){
            JOptionPane.showMessageDialog(this, "Số CCCD không hợp lệ !","Thông báo",2);
            return false;
        }
        
        try{
            int dauNS = Integer.parseInt(ngaysinh.substring(0, 2));
            int cuoiNS = Integer.parseInt(ngaysinh.substring(6));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ !","Thông báo",2);
            return false;
        }
        ArrayList<String> aNgaySinh = new ArrayList<String>();
        String[] a = ngaysinh.split("/");
        for(String i:a)
            aNgaySinh.add(i);
        
        if(aNgaySinh.size() != 3 || aNgaySinh.get(0).length() !=2 || aNgaySinh.get(1).length() !=2 || aNgaySinh.get(2).length() !=4){
            JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ !","Thông báo",2);
            return false;
        }
        
        
        return true;
    }
    public boolean KTSDTVaSCCCD(){
        String sdt = txt_SDT.getText().trim();
        String socccd = txt_SoCCCD.getText().trim();
        int ktsdt = NhanVienDAO.TimSDT(sdt);
        if(ktsdt==1)
        {
            JOptionPane.showMessageDialog(this, "Số điện thoại này đã có !","Thông báo",2);
            return false;
        }
        int ktsocccd = NhanVienDAO.TimSoCCCD(socccd);
        if(ktsocccd==1)
        {
            JOptionPane.showMessageDialog(this, "Số CCCD này đã có !","Thông báo",2);
            return false;
        }
        return true;
    }
    
    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        if(KiemTraTXT() && KTSDTVaSCCCD()){
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    String hoten = txt_HoTen.getText().trim();
                    String sdt = txt_SDT.getText().trim();
                    String diachi = txtA_DiaChi.getText().trim();
                    String manv = txt_MaNV.getText().trim();
                    String socccd = txt_SoCCCD.getText().trim();
                    String ngaysinh = txt_NgaySinh.getText().trim();
                    String quequan = txt_QueQuan.getText().trim();
                    String hinh = txt_Browser.getText().trim();
                    String gt = cbo_GT.getSelectedItem().toString();
                    String sql = "set dateformat dmy\n" +
                                 "insert into NhanVien(MaNV,HoTenNV,GioiTinhNV,SDT_NV,"
                                + "SoCCCD,NgaySinh,DiaChiNV,QueQuan,HinhAnh)\n" +
                                 "values\n" +
                                 "('"+manv+"',N'"+hoten+"',N'"+gt+"','"+sdt+"','"+socccd+"',"
                                + "'"+ngaysinh+"',N'"+diachi+"',N'"+quequan+"',N'"+hinh+"')";
                    int kq=NhanVienDAO.ThemXoaSua(sql);
                    if(kq!=-1)
                    {
                        dsnv = NhanVienDAO.getDSNV();
                        laydulieuNV(dsnv);
                        JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
                    }
                    else
                         JOptionPane.showMessageDialog(this, "Mã nhân viên này đã tồn tại !", "Thông báo", 2);

                }
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        if(txt_MaNV.getText().equals(""))
            JOptionPane.showMessageDialog(this, "mã nhân viên không được để trống !","Thông báo",2);
        else
        {
            if(tbl_NhanVien.getSelectedRowCount()==1)
            {
                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    String manv = txt_MaNV.getText().trim();
                    String sql = "delete from NhanVien where MaNV = '"+manv+"'";
                    if(NhanVienDAO.ThemXoaSua(sql)!=-1)
                    {
                         dsnv = NhanVienDAO.getDSNV();
                        laydulieuNV(dsnv);
                        JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                    }
                    else
                        JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);

                }
            }else{
                if(tbl_NhanVien.getRowCount()==0)
                    JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
                else
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        if(KiemTraTXT()){
            if(tbl_NhanVien.getSelectedRowCount()==1)
            {
                if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                        String hoten = txt_HoTen.getText().trim();
                        String sdt = txt_SDT.getText().trim();
                        String diachi = txtA_DiaChi.getText().trim();
                        String manv = txt_MaNV.getText().trim();
                        String socccd = txt_SoCCCD.getText().trim();
                        String ngaysinh = txt_NgaySinh.getText().trim();
                        String quequan = txt_QueQuan.getText().trim();
                        String hinh = txt_Browser.getText().trim();
                        String gt = cbo_GT.getSelectedItem().toString();
                        String sql = "set dateformat dmy\n" +
                                    "update NhanVien\n" +
                                    "set HoTenNV = N'"+hoten+"', GioiTinhNV = N'"+gt+"', "
                                + "SDT_NV = '"+sdt+"', SoCCCD='"+socccd+"', "
                                + "NgaySinh='"+ngaysinh+"', DiaChiNV = N'"+diachi+"', "
                                + "QueQuan = N'"+quequan+"', HinhAnh = N'"+hinh+"'\n" +
                                    "where MaNV = '"+manv+"'";
                        NhanVienDAO.ThemXoaSua(sql);
                        dsnv = NhanVienDAO.getDSNV();
                        laydulieuNV(dsnv);
                        JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
                }
            }else{
                if(tbl_NhanVien.getRowCount()==0)
                    JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
                else
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    public void clearAllTextField(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JTextField){
                JTextField f = (JTextField)c;
                f.setText("");
            }
            else if(c instanceof Container)
                clearAllTextField((Container)c);
        }
    }
    public void returnDefaultAllCbo(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JComboBox){
                JComboBox f = (JComboBox)c;
                f.setSelectedIndex(0);
            }
            else if(c instanceof Container)
                returnDefaultAllCbo((Container)c);
        }
    }
    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        clearAllTextField(this.getContentPane());
        returnDefaultAllCbo(this.getContentPane());
        lbl_STT.setText("");
        txtA_DiaChi.setText("");
        laydulieuNV(dsnv);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void tbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhanVienMouseClicked
        // TODO add your handling code here:
        String STT = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 0).toString();
        String hoten = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 2).toString();
        String gt = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 3).toString();
        String sdt = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 4).toString();
        String diachi = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 7).toString();
        String manv = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 1).toString();
        String socccd = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 5).toString();
        String ngaysinh = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 6).toString();
        String quequan = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 8).toString();
        String LinkHinh = NhanVienDAO.TimLinkHinh(manv);
        
        
        txt_MaNV.setText(manv);
        txt_SoCCCD.setText(socccd);
        txt_NgaySinh.setText(ngaysinh);
        txt_QueQuan.setText(quequan);
        txtA_DiaChi.setText(diachi);
        txt_HoTen.setText(hoten);
        txt_SDT.setText(sdt);
        if(gt.equals(cbo_GT.getItemAt(0))){
            cbo_GT.setSelectedIndex(0);
        }
        else{
            cbo_GT.setSelectedIndex(1);
        }
        lbl_STT.setText(STT);
        txt_Browser.setText(LinkHinh);
        if(!txt_Browser.getText().equals(""))
        {
            ImageIcon imgicon = new ImageIcon(new ImageIcon(txt_Browser.getText()).getImage().getScaledInstance(130, 140, Image.SCALE_SMOOTH));
            lbl_HinhAnh.setIcon(imgicon);
        }
        else
            lbl_HinhAnh.setIcon(null);
    }//GEN-LAST:event_tbl_NhanVienMouseClicked

    
    private void btn_SapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SapXepActionPerformed
        // TODO add your handling code here:
//        String[] x = {"Mã số","Họ tên","Số điện thoại","Số CCCD"};
        String obj = "";
        if(cbo_SapXep.getSelectedIndex()==0)
            obj = "MaNV";
        else if(cbo_SapXep.getSelectedIndex()==1)
            obj = "HoTenNV";
        else if(cbo_SapXep.getSelectedIndex()==2)
            obj = "SDT_NV";
        else
            obj = "SoCCCD";
        String StyleSort = "";
        if(cbo_LoaiSapXep.getSelectedIndex()==0)
            StyleSort = "asc";
        else
            StyleSort = "desc";
        ArrayList<NhanVien> ResultSort= new  ArrayList<NhanVien>();
        ResultSort = NhanVienDAO.SapXep(obj,StyleSort);            
        laydulieuNV(ResultSort);
    }//GEN-LAST:event_btn_SapXepActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
//        String[] x = {"Mã số","Họ tên","Giới tính","Số điện thoại","Số CCCD","Quê quán"};
        String obj = "";
        String value = "";
        if(cbo_TimKiem.getSelectedIndex()==0){
            obj = "MaNV";
            value = txt_SDT.getText().trim();
        }
        else if(cbo_TimKiem.getSelectedIndex()==1){
            obj = "HoTenNV";
            value = txt_HoTen.getText().trim();
        }
        else if(cbo_TimKiem.getSelectedIndex()==2){
            obj = "GioiTinhNV";
            value = cbo_GT.getSelectedItem().toString();
        }
        else if(cbo_TimKiem.getSelectedIndex()==3){
            obj = "SDT_NV";
            value = txt_SDT.getText().trim();   
        }
        else if(cbo_TimKiem.getSelectedIndex()==4){
            obj = "SoCCCD";
            value = txt_SoCCCD.getText().trim();   
        }else{
            obj = "QueQuan";
            value = txt_QueQuan.getText().trim();
        }
        ArrayList<NhanVien> ResultSearch= new  ArrayList<NhanVien>();
        ResultSearch = NhanVienDAO.TimKiem(obj,value);            
        laydulieuNV(ResultSearch);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void txt_SDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SDTKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_SDTKeyTyped

    private void txt_SoCCCDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoCCCDKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_SoCCCDKeyTyped

    private void txt_NgaySinhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NgaySinhKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String a="/";
        char b = a.charAt(0);
        if (!((c == b) || (Character.isDigit(c)))){
            evt.consume();
        }
    }//GEN-LAST:event_txt_NgaySinhKeyTyped

    private void btn_LinkAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LinkAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("D:\\");
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        txt_Browser.setText(filename);
        ImageIcon imgicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(130, 140, Image.SCALE_SMOOTH));
        lbl_HinhAnh.setIcon(imgicon);
    }//GEN-LAST:event_btn_LinkAnhActionPerformed

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        close();
        FormGiaoDien frmggd = new FormGiaoDien();
        frmggd.setTenTK(lbl_TenTK.getText());
        frmggd.setVisible(true);
    }//GEN-LAST:event_btn_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_LinkAnh;
    private javax.swing.JButton btn_SapXep;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbo_GT;
    private javax.swing.JComboBox<String> cbo_LoaiSapXep;
    private javax.swing.JComboBox<String> cbo_SapXep;
    private javax.swing.JComboBox<String> cbo_TimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_HinhAnh;
    private javax.swing.JLabel lbl_STT;
    private javax.swing.JLabel lbl_TenTK;
    private javax.swing.JTable tbl_NhanVien;
    private javax.swing.JTextArea txtA_DiaChi;
    private javax.swing.JTextField txt_Browser;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_NgaySinh;
    private javax.swing.JTextField txt_QueQuan;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_SoCCCD;
    // End of variables declaration//GEN-END:variables
}
